import sys
import re
from pathlib import Path

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

# Source texts leaf by leaf
source_leaves = {
    191: """=== LEAF p191 ===
фивском), эфиопской и арабской; большая часть этих сведений находится в коптском житии, сохранившемся в рукописи X в. [440]. С этой картиной вполне сходится описание Руфина и Палладия. Это описание относится к тому времени, когда в Тавенниси было уже ок. 3 тыс. монахов и ими управлял прп. Аммон. (кон. IV в.): «иноки принимали пищу с лицем покрытым, опустив глаза вниз, чтобы не видеть, как ест близ сидящий брат; за трапезой все хранили такое строгое молчание, что, казалось, находишься в пустыне; за трапезу садились только для виду, чтобы скрыть свое подвижничество; один раз или два подносили к устам руку, взявши хлеба или маслин, или чего-либо другого, что было предложено на трапезе, и вкусив от каждого яства по одному разу, тем и были довольны; другие, съевши немного хлеба, ни до чего больше не дотрагивались, а иные довольствовались только ложками тремя кашицы (ζωμοῦ)» [441]. В Четыредесятницу тавеннисийские иноки, по словам Палладия, не употребляли вареной пищи; сверх того, иные налагали тогда на себя еще особые подвиги: одни принимали пищу вечером, другие чрез 5 дней, иные всю ночь стояли на молитве, а днем сидели за рукоделием [442].

Когда к прп. Пахомию пришла сестра его Мария, он, отказавшись видеть ее, чрез привратника посоветовал ей поселиться в уединении на значительном расстоянии от Тавенниси, на другой стороне Нила, где построил для нее жилище; около последнего скоро возник женский монастырь с таким же строем жизни, как в мужском; инокини приготовляли для последнего шерстяные одежды и за это получали оттуда средства пропитания. Когда все возраставшее число иноков в Тавенниси сделало тесным монастырь, {с. 203} прп. Пахомий основал другой монастырь неподалеку в местности Певоу, а затем еще 7 монастырей. Всеми ими руководил прп. Пахомий, поселившийся в Певоу. Преподобный часто посещал монастыри. В Певоу иноки других монастырей собирались дважды в год — на Пасху и осенью, когда давали эконому отчет в работах. Здесь крестили в Четыредесятницу оглашенных. Когда в монастырь стало поступать много греков (первоначально в них были одни копты), то посредником (переводчиком) в сношениях их с настоятелем и вместе начальником их сделан был Феодор, бывший чтец Александрийской церкви. Перед смертью прп. Пахомий предложил братии избрать ему преемника, а когда та предоставила это ему, назначил игуменом престарелого Петрония, умершего через месяц и назначившего преемником Орсисия; помощником последнего по управлению многочисленными монастырями прп. Пахомия и настоятелем Певоу сделан был прп. Феодор Освященный († 368 г. ранее Орсисия), основавший неподалеку от Певоу женский монастырь [443].

Внутренний строй Пахомиевых монастырей""",

    192: """=== LEAF p192 ===
Таковы были внешняя сторона и история Пахомиевых монастырей. Внутренняя организация, сообщенная прп. Пахомием своим монастырям, значительно расходилась со всем строем жизни как отшельнической, так и выше перечисленных нижне-египетских монастырей анахоретского типа. Основой здесь была власть, регламентация и кара (епитимия), начала, которыми отшельники в своем духовном руководительстве отказывались пользоваться, а анахоретские монастыри применяли в самом ограниченном размере. Послушание теперь стало главной монашеской добродетелью и все настойчивее восхваляется в аскетической литературе [444]. Когда повара, в отсутствие прп. Пахомия, перестали готовить похлебку по субботам и воскресеньям, вопреки уставу, в виду того, что большинство братий не ели ее, а свободное время употребили на изготовление рогож (главный заработок монастыря), прп. Пахомий (по жалобе одного инока на лишение вареной пищи) велел сжечь 500 выделанных благодаря такой экономии рогож. Брату, сделавшему две рогожи вместо одной в день, прп. Пахомий велел принести их в церковь и просить у братии прощенья и молитв, безвыходно сидеть в келии на хлебе с солью и ежедневно плести по две рогожи. Неисправных иноков прп. Пахомий изгонял из монастыря и в иные годы таких изгнанных было много. Двух самоубийц в женском монастыре прп. Пахомий запретил поминать в молитвах, совершать за них литургию и подавать милостыню, всех же сестер за непредотвращение поступка отлучил от причастия {с. 204} на 7 лет [445]. Новизна или своеобразность таких начал в тогдашней иноческой жизни станет очевидна из сопоставления их со следующими фактами из отшельнической практики.

«Брат просил авву Сисоя: дай мне наставление. Старец сказал: что ты заставляешь меня празднословить? Делай, что видишь на мне» [446].

«Брат пришел однажды к авве Феодору Фермейскому и пробыл при нем три дня, прося у него наставления; но авва не отвечал ему, и брат пошел печальный» [447].

«Один согрешивший брат выслан был пресвитером (игуменом) из церкви; авва Виссарион встал и вышел вместе с ним, говоря: и я также грешник» [448].

Прп. Антоний дважды отправлял изгнанного из киновии монаха в ту же киновию и этим вынудил принять его обратно [449].

«Некогда в Скиту брат впал в грех. Братия, собравшись (Скит, как мы видели, управлялся собранием братий), послали за аввою (отшельником) Моисеем, но он не хотел идти. Тогда послал к нему пресвитер с такими""",

    193: """=== LEAF p193 ===
словами: иди, тебя ожидает собрание. Авва, встав, взял худую корзину, наполнил ее песком, и так пошел. Братия, вышедши к нему на встречу, спрашивают его: что это значит, отец? Старец отвечал им: это грехи мои сыплются позади меня, но я не вижу их, а пришел теперь судить чужие грехи. Братия, услышав это, ничего не стали говорить (согрешившему) брату, но простили его» [450].

Подобное сделал в Скиту по поводу такого же судебного собрания братий авва Пиор: носил по монастырю полную суму песку на плечах в знак своих грехов и немного песку в корзине пред собою в знак грехов павшего брата [451].

«Жил в киновии один отшельник, по имени Тимофей. До настоятеля дошел слух, что один брат подвергся искушению, и он спросил Тимофея: что делать с падшим братом? Отшельник присоветовал выгнать его. Когда же выгнали брата, искушение, бывшее с ним, постигло и Тимофея» [452].

Неудивительно, что у прп. Пахомия в виду такого расхождения принятых им начал для своего общежития с общеподвижнической практикой иногда являлось сомнение в правильности их, но вот как оно было разрешено одним из столпов отшельничества. Прп. Макарий Александрийский (пресвитер Келлий) «пришел к авве Пахомию Тавеннисиотскому. Пахомий спросил его: Если братия не соблюдают порядка, хорошо ли учить их? Авва Макарий отвечал ему: Учи и строго суди своих подчиненных, а из посторонних не суди никого» [453]. Дело Пахомия, по преданию, получило одобрение — уже после смерти его — и от главы отшельничества, {с. 205} прп. Антония [454]. Посетившим его тавеннисиотам прп. Антоний говорил о Пахомии: «Пахомий сослужил Господу великую службу, соединяя все эти полчища и подчиняя их одному правилу в деле служения Господу. До него один человек, по имени Аут, начинал это служение, но как его намерение исходило не из глубины сердца, то он не получил этой благодати» [455]. Строй жизни в Пахомиевом монастыре, как ни разнился он от других монастырей строгостью и регламентацией, однако, не был чрезмерно суров. Он не был рассчитан на одних подвижников высокой силы духа и тела, как отшельничество, но и на средние и даже слабые силы. Когда прп. Макарий Александрийский тайно поступил в Тавеннисиотский монастырь, он сразу же так превзошел всех подвигами, что братия стали роптать на настоятеля за прием его в монастырь: «откуда ты привел к нам сего""",

    194: """=== LEAF p194 ===
бесплотного человека на осуждение наше? или его изгони отсюда, или все мы, да будет тебе известно, сегодня же оставим тебя» [456]. Неудивительно, что в Пахомиевых монастырях не было недостатка в иноках, и они быстро переполнялись; при кончине прп. Пахомия всех монахов в основанных им монастырях насчитывали до 7000 [457].

Устав, данный Ангелом

Такому духу Пахомиева общежития вполне отвечает тот устав, который, по преданию, был дан прп. Пахомию явившимся ему Ангелом на медной доске [458]. Правила эти, определяя вообще жизнь в киновии в снисходительном духе, предоставляют много места частному подвижничеству [459]. {с. 206} Кельи устрой отдельные в одном здании [460], и в каждой из них пусть живут по три инока [461], имея общую трапезу. Спать не лежа, но на покатых седалищах [462]. Одежда — льняной хитон без рукавов (левитон) и на плечах белая козья кожа (милоть) [463], без которой они не должны вкушать пищи и спать; для причащения же пусть снимают ее [464], развязывают пояс [465] и подходят только в левитоне и кукуле; на голове пусть носят кукули [466] с вышитыми крестами пурпурового цвета [467]. Братию раздели на 24 чина по числу букв греческого алфавита, так чтобы каждому чину усвоена была своя буква, начиная с альфы и виты по порядку, так чтобы если настоятелю нужно будет спросить о ком-либо, он мог спросить: как поживает чин альфа или как поживает чин вита? [468]. При этом наименее хитрых и более простых обозначь буквою йота (ι), а непокорных и крутых нравом отметь буквою кси (ξ) [469], выражая таким образом самою""",

    195: """=== LEAF p195 ===
формою буквы свойство наклонностей, нравов и жизни каждого. Знаки сии будут понятны только духовным [470]. Чужестранца иного монастыря не принимать за общую трапезу [471]. В монастырь приходящего не принимать ранее трех лет искуса [472]; по прошествии же трех лет, если он покажет способность к высшим подвигам [473], принять его в монастырь [474]. За трапезой есть с покрытою головою, наклонившись к тарелке и не глядя по сторонам [475]. Молиться положено 12 раз в день, 12 раз вечером, 12 раз в ночи и 3 раза в 9-м часу дня; при каждой молитве положено читать псалом [476]. Когда великий Пахомий сказал на это, что молитв мало, Ангел отвечал: «Я постановил так, чтобы и слабые без отягощения могли исполнять сие правило; совершенные же не имеют нужды в законе; они, пребывая в келиях, всю жизнь свою проводят в созерцании Бога [477]. Устав я дал тем, чей ум {с. 207} еще не зрел, чтобы они, хотя бы как непокорные рабы из страха пред господином, исполняли общее правило жизни и достигали свободы духа» [478].

В таком виде передан этот устав у Палладия (в Лавсаике), Созомена, Дионисия Малого и в арабском Житии прп. Пахомия. Нет оснований сомневаться в историческом существовании такого устава прп. Пахомия, хотя в нем, по-видимому, не все подлинно или точно передано. Во всяком случае переданные правила имеют печать высокой древности, отражая в себе еще живую связь со старым отшельничеством [479]. Таковы в особенности литургические правила этого устава. Характерно предписание совершать в 9-й час 3 молитвы: это напоминает ту молитвенную службу, которая еще у Тертуллиана соединялась с 9-м часом [480]. Своеобразно определение молитв для дня, вечера и ночи по 12 молитв [481]. Это число молитв, как и устав вообще, по преданию, перешло к прп. Пахомию от Ангела, а по другому преданию, передаваемому Кассианом [482], в Египте положено было совершать по 12 псалмов на вечерней и ночной службе по указанию Ангела же, явившегося на одном соборе отцов, нарочито рассуждавшем об этом предмете {с. 208} [483]. Предписание же Ангела в Пахомиевом уставе предварять каждую трапезу молитвою с псалмом, очевидно, имеет в виду ту трапезу, которая соединялась с приобщением св. Таин или следовала за ним [484].

В правилах Ангела затронуты почти все важнейшие стороны монастырской жизни (пища, сон, одежда, прием в монастырь,""",

    196: """=== LEAF p196 ===
управление им), но ограничиваются о каждой из них самыми общими и принципиальными правилами, не входя в подробности. В них нет следов деления монахов по «домам» и должностей, кроме аввы, хотя в «Житиях» Пахомия все это предполагается. Поэтому правила Ангела можно признать за первоначальный набросок устава, данный прп. Пахомием своему монастырю. Относительно богослужения они определяют число молитв, но не дают чина их; очевидно, чин был предоставлен личному усмотрению каждого или обычаю. О литургии и часах, кроме 9-го, правила вовсе не говорят. Но в правилах упоминается о «причащении», которое должно было происходить, очевидно, на литургии. Литургия могла совершаться по субботам и воскресеньям, когда, по словам «Житий» Пахомия, в монастырь приходил священник или братия шли в соседнюю церковь. Но для других дней правила Ангела не упоминают о литургии; взамен ее они назначают 12 дневных молитв. По свидетельству прп. Иоанна {с. 209} Кассиана, наблюдавшего жизнь египетских монастырей в конце IV в., в них совершались общественные службы только дважды в день — вечером и ночью: «во всем Египте и Фиваиде число псалмов для вечерних и ночных собраний определяется двенадцатью» [485]. Дневные же службы (кроме литургии в субботу и воскресенье) Кассиан считает позднейшим нововведением, допущенным первоначально в Палестине и Месопотамии, а отсюда уже перешедшим в Египет. Таким образом Пахомиев устав Ангела назначал молитвы для тех именно служб, которые совершались тогда в Египте (вечерняя, ночная и 9 час), и вместо литургии будничных дней вводил «дневные молитвы». Так как в киновиях Пахомия не было священника, а правила запрещали инокам стремиться к священству, то отсутствие ежедневной литургии в них было совершенно естественно. Это обстоятельство и заставляло Пахомиевы монастыри, желавшие безвыходно пребывать в монастыре без пресвитера [486], вводить особые службы, более однообразные, но, конечно, не менее продолжительные.""",

    197: """=== LEAF p197 ===
Если эти службы могли казаться небольшими («молитв мало», возражает Пахомий Ангелу), то по сравнению лишь с молитвенным правилом отшельников, которые, как авва Паламон, молились по 60 раз днем и 60 раз ночью [487].

Правила прп. Пахомия в позднейших редакциях

Правила Ангела могли удовлетворять монастырь только на первых порах его существования. С ростом монастыря и умножением монастырей потребовалась более детальная регламентация жизни. «Жития» прп. Пахомия свидетельствуют, что он дал своим монастырям подробный письменный устав, который читался братии и заучивался ими наизусть [488]. Но нельзя того же сказать о другом, более обширном сборнике Пахомиевых правил. Этот {с. 210} сборник известен ныне в трех редакциях. 1) «Правила (Regula) св. Пахомия», переведенные на лат. яз. блж. Иеронимом [489] (ок. 404 г.) для монахов-латинян Пахомиева монастыря в Канопе близ Александрии. В этих правилах даются подробные предписания относительно монастырской жизни, но черт сходства с картиной жизни в Тавенниси, как рисуется она в «Житиях» первоначальников общежития мало. Вообще «Правила» блж. Иеронима представляют не столько первоначальный устав Тавенниси, сколько позднейшую его кодификацию, сложившуюся в течение IV века под влиянием местных потребностей различных Пахомиевых монастырей. Об этом свидетельствует уже то, что эти «Правила» не упоминают ни о письменах Ангела, ни о 12 молитвах, столь твердо засвидетельствованных о Тавенниси, как «Житиями» [490], так и Лавсаиком. 2) Другая редакция «Правил» прп. Пахомия, тоже сохранившаяся в латинском переводе, заключает в себе те же правила, но расположенные в ином порядке и изложенные яснее, чем у блж. Иеронима [491]. 3) Самая краткая редакция «Правил» заключает их только 50, причем правила кратки (особенно в начале) и лишены позднейших наслоений; по тону и духу они производят впечатление большой древности [492]. Но несомненная подлинность принадлежит только тем правилам, которые засвидетельствованы «Житиями» прп. Пахомия и древними церковными историками (Руфином, Палладием, Созоменом).

Правила прп. Пахомия, переведенные блж. Иеронимом

Эта редакция распадается на 194 правила (praecepta), которым предпосланы еще 16 правил (praecepta et instituta), 18 правил (praecepta atque judicia) и 11 правил (praecepta ac leges). Все это переведено блж. Иеронимом с греческого перевода с коптского оригинала, так что блж. Иероним переводил уже не с подлинника, а с перевода, сделанного иноками Александрийского монастыря с египетского языка на греческий. Правила излагаются без системы [493]. Они снабжены блж. Иеронимом кратким предисловием, в котором он дает общий очерк жизни в Пахомиевых монастырях и объясняет поводы к своему переводу.

«В каждом Пахомиевом монастыре», замечает блж. Иероним в предисловии к переводу «Правил», «есть отец (авва), эконом, седмичные,""",

    198: """=== LEAF p198 ===
слуги и смотрители отдельно для каждого дома; в доме живут по 40 или более или менее братий, повинующихся одному настоятелю; в монастыре же бывает 30 или 40 домов, которые соединяются в три или четыре разряда (tribus), так чтобы работающие в одном мастерстве составляли один разряд». Сам авва монастыря избирался братиею или назначался предшественником; он имел высшую власть в монастыре, но делил ее с собранием старших и экономом; он назначал смотрителей домов (пр. 159), назначал работы братиям по способностям (пр. 49), перемещал братий из дома в дом (пр. 83), разрешал отлучки из монастыря (пр. 52, 93), судил виновных и утверждал епитимьи, {с. 211} наложенные смотрителями (пр. 147, 151, 164). Заместителем аввы был второй после него (secundus), обязанности которого ближе не определяются в правилах [494]. Смотритель дома (praepositus domi) имел ближайший надзор за иноками своего дома, которые без его позволения ничего не смели предпринимать (пр. 157), даже ходить по монастырю (пр. 84, 52), или пойти в келию брата (пр. 127); он получал и раздавал материалы для работ, требовал отчета в них и сам давал его (пр. 26, 146, 123). У каждого смотрителя был помощник (secundus), который заступал его место во время его отлучки или болезни и заведовал домашними делами (пр. 66, 70, 95). Денежная часть в монастыре лежала на экономе, который имел помощника — расходчика. Правила дают полную картину монастырской дисциплины. Они подробно определяют отношение инока к монастырскому имуществу, которое должно беречься, как священное (пр. 148, 149), правила поведения братий во время молитвы (пр. 49). Среди братий он всюду занимал место по времени поступления в монастырь (пр. 1). Затем новопоступивший должен был выучить наизусть молитвы и правила монастырские (пр. 139, 140); для этого к нему приходил в 3, 6 и 9 часу старший и, стоя пред ним, повторял за ним слова (пр. 139); наконец новоначальный должен был выучить наизусть по меньшей мере Псалтирь и Новый Завет (пр. 140). Вся жизнь инока протекала под постоянным надзором и строжайшим послушанием; малейшее нарушение правил не оставлялось без наказания, епитимьи. Степени епитимьи были различны — начиная от внушения старшего (пр. 102, 148 и др.) и кончая""",

    199: """=== LEAF p199 ===
изгнанием из монастыря; наиболее употребительные епитимьи — стояние, когда другие сидят (пр. 8, 22, 31 и др.), стояние без пояса с опущенной головой или руками (пр. 9 и др.); применялись и телесные наказания (за кражу — пр. 149). Нарушение правил предупреждалось также тем, что никто из братий не имел права оставаться в келии один, без смотрителя дома или старшего над работой {с. 212} недельного (пр. 88, 107), а вне монастыря инок должен был идти непременно с другим иноком, назначенным отцом монастыря и обязанным наблюдать за ним (пр. 62, 63). «Правила» подробно регламентируют и работы иноков. О плетении рогож, о котором так часто говорят «Жития», почти исключительно говорят «Правила», почти не касаясь других; они подробно определяют, сколько рогож должен свить инок в день (пр. 12, 26, 27, 74, 145–147, 177). Ходили на работы и за монастырь — резать ветви, собирать дрова, травы для соления, финики (пр. 78). И на этих работах иноки находились под постоянным руководством опытных (пр. 116, 145, 68, 134). Что касается одежды и обуви, то кроме хитона (левитона), милоти и кукуля, называемых в «Уставе» Ангела, «Правила» упоминают нарамник (= параман), короткую мантию, сандалии и посох (предисл. и пр. 81); хитонов положено иметь два, из которых один без рукавов; кукулия и милоти (пр. 91); мантия одевалась только в церковь; сандалии скидались при входе в церковь и трапезу (пр. 101). Каждой из этих вещей инок пользовался с ведома и позволения смотрителя; стирать одежды дозволялось только в определенные дни по указанию смотрителя (пр. 67–73). Пища выдавалась по указанию смотрителя (пр. 23). Обычную пищу составляли хлеб, сыр, овощи и вареная трава (pulmentum), маслины, сушеные финики, мелкие соленые рыбки и соус (liquamen) из особого рода трав, просоленных с уксусом (пр. 80); при выходе из монастыря братия получали хлеб, соленые маслины и сыр (пр. 80). Пища готовилась дважды в день — в обед и ужин; хлеб выдавался в келии, каждый раз на три дня (пр. 37–40). Другую пищу запрещалось вкушать даже в дороге и у родных (пр. 46, 54). Вино и рыба дозволялись""",

    200: """=== LEAF p200 ===
только больным (пр. 45). «Кто не захочет идти в трапезу (для воздержания), получает в свою келию только хлеб, воду и соль на день или на два дня» (пр. 37). Кроме установленных часов трапезы, запрещалось вкушать пищу (пр. 75). Ночью до рассвета (проснувшись) запрещалось пить воду (пр. 87). «Другие дни (кроме среды и пятницы, когда постились до вечера) одни вкушают пищу в полдень, другие вечером, а другие довольствуются раз {с. 213} принятою в обед или ужин пищею... Сидя за столом, никто не должен смотреть на других, но опустив глаза в свою тарелку, размышлять о Боге или слушать, как чтец читает что-либо из Писания» (пр. 36). Опоздавший, разговаривающий или смеющийся за трапезою подвергался епитимьи (пр. 31, 33). По выходе из трапезы инок должен был идти прямо в свою келию, не останавливаясь для разговора с другим (пр. 34).

Молитвою и богослужением «Правила» не занимаются специально, упоминая о них лишь мимоходом. О так называемых «дневных молитвах» замечается, что они совершались в полдень (пр. 24). Кроме того, «Правила» упоминают об утренней молитве в час рассвета (пр. 20), 6 вечерних молитвах (пр. 34, 121, 125), но это должно быть вечерние домашние молитвы в каждом доме; взамен вечерни на открытом месте в Уставе Ангела, как мы видели, положено 12, а по другим только 6 молитв. По окончании утренней молитвы в каждом доме братия обсуждали, что говорил смотритель (пр. 20). Если молитва совершалась в церкви, то о времени собрания в церковь и выхода к ней давался звон в било недельным по благословению аввы (пр. 24); этот недельный следил и за порядком в церкви (пр. 143). По знаку била братия выходили из келий, шепча или повторяя что-либо наизусть из Писания и размышляя об этом (пр. 3). Для пения псалмов в церкви вызывался каждый по чину и пел не более одного псалма; кто спутывался в пении, нес епитимию (пр. 13, 14, 17, 127). Упоминается о чтениях (Писания) на молитвах (пр. 13). Под угрозою епитимьи запрещалось на молитвах церковных и домашних смеяться, разговаривать, шептать, кашлять, зевать и т. п. (пр. 7, 121), а также смотреть на других, как кто молится (пр. 7). Преклонять колена (для молитвы после пения псалма) нужно было не иначе, как вслед за"""
}

# Draft texts leaf by leaf
draft_leaves = {
    191: """=== LEAF p191 ===
Thebaic), Ethiopic, and Arabic; the greater part of this information is found in the Coptic *Life*, preserved in a 10th-century manuscript [^1024]. With this picture the description of Rufinus and Palladius fully agreeth. This description pertaineth unto that time when in Tabennisi there were already about 3,000 monks and they were governed by St. Ammon (end of the 4th c.): "the monks took food with their faces covered, casting their eyes down, that they might not see how a brother sitting near was eating; at table all kept such strict silence that it seemed as though one were in the desert; they sat down at table only for appearance' sake, in order to conceal their asceticism; once or twice they would raise their hand unto their mouth, taking bread or olives or whatever else was offered at table, and having tasted of each dish a single time, therewith were content; others, having eaten a little bread, touched nothing further; while others contented themselves with only three spoonfuls of gruel (*zōmou*)" [^1025]. During the Forty Days' Fast (Great Lent) the Tabennesiot monks, according unto the words of Palladius, did not partake of cooked food; moreover, certain ones then took upon themselves yet special ascetic labors: some took food in the evening, others after five days, while others stood all night at prayer and during the day sat at handiwork [^1026].

When the sister of St. Pachomius, Mary, came unto him, he, refusing to see her, advised her through the gatekeeper to settle in solitude at a considerable distance from Tabennisi, on the other side of the Nile, where he built a dwelling for her; around the latter there soon arose a convent of women with the same order of life as in the monastery of men; the nuns prepared woolen garments for the latter and in return received from thence the means of subsistence. When the ever increasing number of monks in Tabennisi rendered the monastery cramped, *(Orig. p. 203)* St. Pachomius founded another monastery not far off in the locality of Pbow (Faou), and thereafter yet seven monasteries. Over all of them St. Pachomius had direction, having settled in Pbow. The venerable father frequently visited the monasteries. In Pbow the monks of the other monasteries assembled twice a year—at Pascha and in the autumn, when they rendered an account of their labors unto the steward (*oikonomos*). Here they baptized catechumens during the Forty Days' Fast. When many Greeks began to enter the monastery (originally there were only Copts in them), Theodore, a former reader of the church of Alexandria, was appointed intermediary (interpreter) in their relations with the superior and likewise their head. Prior unto his death St. Pachomius proposed unto the brethren to choose a successor for him, and when they left this choice unto him, he appointed as hegumen the aged Petronius, who fell asleep after a month and appointed Orsisius (Horsiesius) as his successor; as assistant of the latter in the governance of the numerous monasteries of St. Pachomius and as superior of Pbow there was appointed St. Theodore the Consecrated († 368, prior unto Orsisius), who founded not far from Pbow a convent of women [^1027].

##### The Internal Order of the Pachomian Monasteries""",

    192: """=== LEAF p192 ===
Such were the external aspect and history of the Pachomian monasteries. The internal organization imparted by St. Pachomius unto his monasteries diverged considerably from the entire order of life both of anchoritism and of the above-enumerated Lower Egyptian monasteries of anchoritic type. The foundation here was authority, regimentation, and punishment (penance), principles that the anchorites in their spiritual direction refused to employ, while the anchoritic monasteries applied them only in the most restricted measure. Obedience now became the primary monastic virtue and is praised ever more insistently in ascetic literature [^1028]. When the cooks, during the absence of St. Pachomius, ceased preparing cooked broth on Saturdays and Sundays, contrary unto the typikon, seeing that the majority of the brethren did not eat it, and employed their free time in the fabrication of mats (the chief earnings of the monastery), St. Pachomius (upon the complaint of a certain monk concerning the deprivation of cooked food) ordered 500 mats woven through such economy to be burned. Unto a brother who had woven two mats instead of one in a day, St. Pachomius ordered him to bring them into church and ask forgiveness and prayers of the brethren, to sit without going forth in his cell upon bread and salt, and daily to weave two mats. Uncorrected monks St. Pachomius expelled from the monastery, and in certain years there were many such expulsions. Two suicides in the convent of women St. Pachomius forbade to be commemorated in prayers, or to celebrate the Liturgy for them, or to distribute alms, while all the sisters, for failing to prevent the deed, he excommunicated from communion *(Orig. p. 204)* for seven years [^1029]. The novelty or distinctiveness of such principles in the monastic life of that era will become evident from comparing them with the following facts from anchoritic practice:

"A brother asked Abba Sisoes: 'Give me an instruction.' The elder said: 'Why compellest thou me to speak vain words? Do what thou seest in me'" [^1030].

"A brother came once unto Abba Theodore of Pherme and remained with him three days, asking an instruction of him; yet the abba answered him not, and the brother departed sorrowful" [^1031].

"A certain sinning brother was cast out by the presbyter (hegumen) from the church; Abba Bessarion arose and went out together with him, saying: 'I too am a sinner'" [^1032].

St. Anthony twice sent back a monk expelled from a cenobium unto that same cenobium and thereby constrained them to receive him back [^1033].

"Once in Scete a brother fell into sin. The brethren, having assembled (Scete, as we have seen, was governed by an assembly of the brethren), sent for Abba (the hermit) Moses, yet he did not wish to go. Then the presbyter sent unto him with these""",

    193: """=== LEAF p193 ===
words: 'Come, the assembly awaiteth thee.' The abba, arising, took a damaged basket, filled it with sand, and thus departed. The brethren, coming forth to meet him, ask him: 'What meaneth this, father?' The elder replied unto them: 'These are my sins pouring out behind me, yet I see them not, and I have come now to judge the sins of another.' The brethren, hearing this, said nothing further unto the (sinning) brother, but forgave him" [^1034].

A similar thing did Abba Pior in Scete on the occasion of such a judicial assembly of the brethren: he carried about the monastery a full sack of sand upon his shoulders in token of his own sins and a little sand in a basket before him in token of the sins of the fallen brother [^1035].

"There dwelt in a cenobium a certain hermit, Timothy by name. Rumor reached the superior that a brother had undergone temptation, and he asked Timothy: 'What is to be done with the fallen brother?' The hermit counseled him to expel him. When however they had expelled the brother, the temptation that had been with him befell Timothy also" [^1036].

It is not surprising that in St. Pachomius, in view of such divergence of the principles adopted by him for his cenobium from general ascetic practice, doubt sometimes arose as to their correctness; yet behold how it was resolved by one of the pillars of anchoritism. St. Macarius of Alexandria (presbyter of Kellia) "came unto Abba Pachomius of Tabennisi. Pachomius asked him: 'If the brethren observe not order, is it good to instruct them?' Abba Macarius replied unto him: 'Instruct and strictly judge thy subordinates, yet of strangers judge no one'" [^1037]. The work of Pachomius, according unto tradition, received approbation—already after his death—likewise from the head of anchoritism, *(Orig. p. 205)* St. Anthony [^1038]. Unto the Tabennesiots who visited him St. Anthony spoke concerning Pachomius: "Pachomius hath rendered a great service unto the Lord, uniting all these hosts and subordinating them unto a single rule in the work of serving the Lord. Before him a certain man, named Aut, began this service, but because his intention proceeded not from the depth of his heart, he did not receive this grace" [^1039]. The order of life in the Pachomian monastery, however much it differed from other monasteries in strictness and regimentation, was nonetheless not excessively harsh. It was calculated not only for ascetics of lofty strength of spirit and body, like anchoritism, but likewise for average and even feeble powers. When St. Macarius of Alexandria entered the Tabennesiot monastery secretly, he straightway so far surpassed all in ascetic labors that the brethren began to murmur against the superior for receiving him into the monastery: "From whence hast thou brought unto us this""",

    194: """=== LEAF p194 ===
incorporeal man unto our condemnation? Either cast him out from hence, or all of us, be it known unto thee, this very day will depart from thee" [^1040]. It is not surprising that in the Pachomian monasteries there was no lack of monks, and they rapidly overflowed; at the falling asleep of St. Pachomius all the monks in the monasteries founded by him were numbered at up to 7,000 [^1041].

##### The Typikon Given by the Angel

Unto such a spirit of the Pachomian cenobium fully correspondeth that typikon which, according unto tradition, was given unto St. Pachomius by an Angel who appeared unto him with a bronze tablet [^1042]. These rules, defining in general the life in the cenobium in a lenient spirit, afford much place for private asceticism [^1043]. *(Orig. p. 206)* Build separate cells within a single structure [^1044], and in each of them let three monks dwell [^1045], having a common meal. Let them sleep not lying down, but upon sloping seats [^1046]. Clothing: a linen tunic without sleeves (*leviton*) and upon the shoulders a white goatskin (*melote*) [^1047], without which they must neither take food nor sleep; yet for communion let them take it off [^1048], untie the girdle [^1049], and draw near only in the *leviton* and cowl (*koukoulion*); upon their heads let them wear cowls [^1050] with embroidered crosses of purple color [^1051]. Divide the brethren into 24 ranks according unto the number of the letters of the Greek alphabet, so that unto each rank its own letter be assigned, beginning from *alpha* and *beta* in order, so that if the superior need to ask concerning anyone, he may ask: 'How fareth the rank of *alpha*?' or 'How fareth the rank of *beta*?' [^1052]. Therewith designate the least cunning and simpler ones by the letter *iota* (ι), and the insubordinate and intractable of disposition mark with the letter *xi* (ξ) [^1053], expressing in this manner by the very""",

    195: """=== LEAF p195 ===
form of the letter the property of the inclinations, morals, and life of each. These signs shall be understandable only unto the spiritual [^1054]. A stranger from another monastery is not to be admitted unto the common meal [^1055]. One coming unto the monastery is not to be received prior unto three years of probation [^1056]; yet after the passing of three years, if he show capacity for higher ascetic labors [^1057], let him be received into the monastery [^1058]. At table eat with covered head, leaning down toward the dish and not looking about [^1059]. It is appointed to pray 12 times by day, 12 times in the evening, 12 times at night, and 3 times at the 9th hour of the day; at each prayer it is appointed to recite a psalm [^1060]. When the great Pachomius said unto this that the prayers were few, the Angel replied: "I have ordained it thus that the weak also without burden may fulfill this rule; for the perfect have no need of a law; they, abiding in their cells, spend their entire life in the contemplation of God [^1061]. A typikon I have given unto those whose mind *(Orig. p. 207)* is not yet mature, that they, even as insubordinate slaves out of fear of their master, may fulfill the common rule of life and attain freedom of spirit" [^1062].

In such form is this typikon transmitted in Palladius (in the *Lausiac History*), Sozomen, Dionysius Exiguus, and in the Arabic *Life of St. Pachomius*. There are no grounds to doubt the historical existence of such a typikon of St. Pachomius, although in it, seemingly, not all is authentic or accurately transmitted. In any case the transmitted rules bear the stamp of high antiquity, reflecting in themselves a still living connection with the old anchoritism [^1063]. Such in particular are the liturgical rules of this typikon. Characteristic is the prescription to celebrate at the 9th hour 3 prayers: this calleth to mind that prayer office which already in Tertullian was joined with the 9th hour [^1064]. Distinctive is the determination of prayers for the day, evening, and night at 12 prayers each [^1065]. This number of prayers, as also the typikon in general, according unto tradition, passed unto St. Pachomius from an Angel, whereas according unto another tradition, transmitted by Cassian [^1066], in Egypt it was appointed to celebrate 12 psalms at the evening and night offices likewise by the direction of an Angel, who appeared at a council of the fathers purposely deliberating upon this matter *(Orig. p. 208)* [^1067]. The prescription of the Angel in the Pachomian typikon to preface each meal by a prayer with a psalm evidently hath in view that meal which was joined with the communion of the Holy Mysteries or followed after it [^1068].

In the rules of the Angel almost all the most important aspects of monastic life are touched upon (food, sleep, clothing, reception into the monastery,""",

    196: """=== LEAF p196 ===
its governance), yet they restrict themselves concerning each of them unto the most general and principled rules, without entering into particulars. In them there are no traces of the division of the monks by "houses" or of offices, except that of the abba, although in the *Lives* of Pachomius all this is presupposed. Therefore the rules of the Angel may be recognized as the initial sketch of the typikon given by St. Pachomius unto his monastery. Concerning divine worship they define the number of prayers, yet give no order (*ordo*) for them; evidently the *ordo* was left unto the personal discretion of each or unto custom. Concerning the Liturgy and the Hours, except the 9th, the rules make no mention whatever. Yet in the rules mention is made of "communion," which had to take place, evidently, at the Liturgy. The Liturgy could be celebrated on Saturdays and Sundays, when, according unto the words of the *Lives* of Pachomius, a priest came unto the monastery or the brethren went unto the neighboring church. Yet for other days the rules of the Angel make no mention of the Liturgy; in place of it they appoint 12 day prayers. According unto the testimony of St. John *(Orig. p. 209)* Cassian, who observed the life of the Egyptian monasteries at the end of the 4th century, in them public services were celebrated only twice a day—in the evening and at night: "throughout all Egypt and the Thebaid the number of psalms for the evening and night assemblies is determined at twelve" [^1069]. The day offices (except the Liturgy on Saturday and Sunday) Cassian regardeth as a later innovation, permitted originally in Palestine and Mesopotamia, and from thence passing over into Egypt. Thus the Pachomian Typikon of the Angel appointed prayers for precisely those offices which were then celebrated in Egypt (evening, night, and the 9th Hour), and instead of the weekday Liturgy introduced "day prayers." Since in the cenobia of Pachomius there was no priest, and the rules forbade the monks to aspire unto the priesthood, the absence of a daily Liturgy in them was wholly natural. This circumstance indeed constrained the Pachomian monasteries, which desired to remain secluded in the monastery without a presbyter [^1070], to introduce special services, more uniform, yet, of course, no less prolonged.""",

    197: """=== LEAF p197 ===
If these services could appear small ("the prayers are few," Pachomius objecteth unto the Angel), it was solely by comparison with the prayer rule of the anchorites, who, like Abba Palamon, prayed 60 times by day and 60 times by night [^1071].

##### The Rules of St. Pachomius in Later Recensions

The rules of the Angel could satisfy the monastery only in the initial stages of its existence. With the growth of the monastery and the multiplication of monasteries, a more detailed regimentation of life was required. The *Lives* of St. Pachomius testify that he gave unto his monasteries a detailed written typikon, which was read unto the brethren and learned by them by heart [^1072]. Yet one cannot say the same concerning another, more extensive collection of Pachomian rules. This *(Orig. p. 210)* collection is known today in three recensions. 1) The *Rules* (*Regula*) of St. Pachomius, translated into Latin by Blessed Jerome [^1073] (ca. 404) for the Latin monks of the Pachomian monastery in Canopus near Alexandria. In these rules detailed prescriptions concerning monastic life are given, yet there are few features of similarity with the picture of life in Tabennisi as it is depicted in the *Lives* of the originators of the cenobium. In general the *Rules* of Blessed Jerome represent not so much the original typikon of Tabennisi as its later codification, formed in the course of the 4th century under the influence of local needs of diverse Pachomian monasteries. Unto this testifieth already the fact that these *Rules* mention neither the letters of the Angel nor the 12 prayers, so firmly attested concerning Tabennisi both by the *Lives* [^1074] and by the *Lausiac History*. 2) Another recension of the *Rules* of St. Pachomius, likewise preserved in Latin translation, containeth the same rules, yet arranged in a different order and set forth more clearly than in Blessed Jerome [^1075]. 3) The briefest recension of the *Rules* containeth only 50 of them, the rules being brief (especially in the beginning) and destitute of later accretions; in tone and spirit they produce the impression of great antiquity [^1076]. Yet indubitable authenticity belongeth only unto those rules that are attested by the *Lives* of St. Pachomius and ancient church historians (Rufinus, Palladius, Sozomen).

###### The Rules of St. Pachomius Translated by Blessed Jerome

This recension falleth into 194 rules (*praecepta*), which are prefaced further by 16 rules (*praecepta et instituta*), 18 rules (*praecepta atque judicia*), and 11 rules (*praecepta ac leges*). All this was translated by Blessed Jerome from a Greek translation from the Coptic original, so that Blessed Jerome translated no longer from the original, but from a translation made by the monks of the Alexandrian monastery from the Egyptian language into Greek. The rules are set forth without system [^1077]. They are provided by Blessed Jerome with a brief preface wherein he giveth a general sketch of life in the Pachomian monasteries and explaineth the motives for his translation.

"In every Pachomian monastery," remarketh Blessed Jerome in the preface unto the translation of the *Rules*, "there is a father (abba), a steward (*oeconomus*), weekly servers (*hebdomadarii*),""",

    198: """=== LEAF p198 ===
ministers, and housemasters (*praepositi*) separately for each house; in a house there dwell 40 or more or fewer brethren, obeying a single superior; while in a monastery there are 30 or 40 houses, which are united into three or four classes (*tribus*), so that those working at the same craft constitute one class." The abba of the monastery himself was chosen by the brethren or appointed by his predecessor; he possessed supreme authority in the monastery, yet shared it with the assembly of the elders and the steward; he appointed the housemasters (Rule 159), assigned labors unto the brethren according unto their abilities (Rule 49), transferred brethren from house to house (Rule 83), permitted leaves of absence from the monastery (Rules 52, 93), judged offenders, and confirmed the penances *(Orig. p. 211)* imposed by the housemasters (Rules 147, 151, 164). The deputy of the abba was the second after him (*secundus*), whose duties are not more closely defined in the rules [^1078]. The housemaster (*praepositus domus*) exercised immediate supervision over the monks of his house, who without his permission dared undertake nothing (Rule 157), even walking about the monastery (Rules 84, 52), or going into the cell of a brother (Rule 127); he received and distributed materials for labors, demanded an accounting thereof, and himself rendered it (Rules 26, 146, 123). Each housemaster had an assistant (*secundus*), who took his place during his absence or illness and had charge of domestic affairs (Rules 66, 70, 95). The financial administration in the monastery rested upon the steward, who had an assistant—the dispenser (*dispensator*). The rules afford a complete picture of monastic discipline. They define in detail the relation of the monk unto the property of the monastery, which was to be guarded as sacred (Rules 148, 149), and the rules of conduct of the brethren during prayer (Rule 49). Among the brethren each everywhere occupied a place according unto the time of his entrance into the monastery (Rule 1). Furthermore, the newly entered monk had to learn by heart the prayers and rules of the monastery (Rules 139, 140); for this purpose there came unto him at the 3rd, 6th, and 9th hours a senior monk, and standing before him, repeated the words after him (Rule 139); finally the novice had to learn by heart at least the Psalter and the New Testament (Rule 140). The entire life of the monk passed under constant surveillance and the strictest obedience; the slightest infraction of the rules was not left without punishment, penance. The degrees of penance were diverse—beginning from the admonition of a senior (Rules 102, 148, etc.) and ending with""",

    199: """=== LEAF p199 ===
expulsion from the monastery; the most customary penances were standing while others sat (Rules 8, 22, 31, etc.), standing without girdle with bowed head or hands lowered (Rule 9, etc.); corporal punishments were likewise employed (for theft—Rule 149). Infraction of the rules was prevented also by this: that none of the brethren had the right to remain alone in the cell without the housemaster or the senior over the weekly labor *(Orig. p. 212)* (Rules 88, 107), while outside the monastery a monk had to go unconditionally with another monk appointed by the father of the monastery and obliged to keep watch over him (Rules 62, 63). The *Rules* regulate in detail also the labors of the monks. Concerning the weaving of mats, whereof the *Lives* speak so frequently, the *Rules* speak almost exclusively, scarcely touching upon other crafts; they define in detail how many mats a monk had to weave in a day (Rules 12, 26, 27, 74, 145–147, 177). They went unto labors outside the monastery as well—to cut reeds, gather firewood, herbs for pickling, and dates (Rule 78). And at these labors the monks were under the constant direction of the experienced (Rules 116, 145, 68, 134). As regards clothing and footwear, beside the tunic (*leviton*), sheepskin (*melote*), and cowl (*koukoulion*) mentioned in the Typikon of the Angel, the *Rules* mention the humeral scapular (*paramand*), a short mantle, sandals, and a staff (preface and Rule 81); of tunics it was appointed to have two, of which one was without sleeves, as well as cowls and sheepskins (Rule 91); the mantle was put on only for church; sandals were removed upon entering the church and refectory (Rule 101). Each of these articles the monk used with the knowledge and permission of the housemaster; washing garments was permitted only on designated days by direction of the housemaster (Rules 67–73). Food was distributed by direction of the housemaster (Rule 23). The customary food consisted of bread, cheese, vegetables, and cooked herbs (*pulmentum*), olives, dried dates, small salted fish, and sauce (*liquamen*) made of a special kind of herbs salted with vinegar (Rule 80); upon departing from the monastery the brethren received bread, salted olives, and cheese (Rule 80). Food was prepared twice a day—at dinner and supper; bread was distributed in the cells, each time for three days (Rules 37–40). Any other food was forbidden to be eaten even on journeys and at relatives' houses (Rules 46, 54). Wine and fish were permitted""",

    200: """=== LEAF p200 ===
only unto the sick (Rule 45). "Whosoever desireth not to go unto the refectory (for the sake of abstinence), receiveth into his cell only bread, water, and salt for one day or for two days" (Rule 37). Beside the appointed hours of the meal, it was forbidden to taste food (Rule 75). At night before dawn (upon awakening) it was forbidden to drink water (Rule 87). "On other days (beside Wednesday and Friday, when they fasted until evening) some take food at midday, others in the evening, while others content themselves with food taken once *(Orig. p. 213)* at dinner or supper... Sitting at table, none ought to look upon others, but casting his eyes down unto his plate, meditate upon God or listen as the reader readeth something from Scripture" (Rule 36). One arriving late, conversing, or laughing at table was subjected unto penance (Rules 31, 33). Upon departing from the refectory the monk had to go straightway unto his cell, without stopping for conversation with another (Rule 34).

With prayer and divine worship the *Rules* do not occupy themselves specifically, mentioning them only in passing. Concerning the so-called "day prayers" it is observed that they were celebrated at midday (Rule 24). In addition, the *Rules* mention morning prayer at the hour of dawn (Rule 20) and six evening prayers (Rules 34, 121, 125), yet these must be evening domestic prayers in each house; in place of Vespers in an open place in the Typikon of the Angel, as we have seen, 12 prayers were appointed, or according unto others only 6. At the conclusion of morning prayer in each house the brethren discussed what the housemaster had said (Rule 20). If prayer was celebrated in church, the time for assembling in church and going forth unto it was signaled by the striking of the semantron (*klepalo*) by the weekly server with the blessing of the abba (Rule 24); this weekly server watched also over order in church (Rule 143). At the signal of the semantron the brethren went forth from their cells, whispering or repeating something by heart from Scripture and meditating upon it (Rule 3). For the singing of psalms in church each was called forth according unto rank and sang no more than one psalm; whosoever stumbled in singing bore penance (Rules 13, 14, 17, 127). Mention is made of readings (from Scripture) at prayers (Rule 13). Under penalty of penance it was forbidden at church and domestic prayers to laugh, converse, whisper, cough, yawn, and the like (Rules 7, 121), as well as to look upon others, how anyone prayeth (Rule 7). To bend the knees (for prayer following the chanting of a psalm) was necessary only after"""
}

# Footnotes mapping
footnotes_list = [
    (1024, "Palladius, Archimandrite (Bishop), *St. Pachomius the Great and the First Monastic Cenobium: According unto Newly Discovered Coptic Documents* (*Sv. Pakhomiy V. i pervoe inocheskoe obshchezhitie: Po novootkrytym koptskim dokumentam*), Kazan, 1899, pp. 18, 39, 44–46, 48, 61–70, 122."),
    (1025, "Rufinus, *Historia Monachorum in Aegypto*, ch. 3; Palladius, *Historia Lausiaca*, ch. 48 (43)."),
    (1026, "Palladius, *Historia Lausiaca*, ch. 19."),
    (1027, "Bishop Palladius, *St. Pachomius the Great*, pp. 77–86, 92, 163, 169, 179, 187."),
    (1028, 'In St. Anthony: "Submission with abstinence subdueth wild beasts" (*Apophthegmata Patrum*, Anthony, § 35). St. John, disciple of Paul (probably 5th c.), by reason of obedience bindeth Gehenna (*ibid.*, John the Disciple of Paul). According unto St. Rufus, in the first heavenly rank standeth the sick man who giveth thanks unto God; in the second, the benefactor; in the third, the hermit; in the fourth and highest, the obedient (*ibid.*, Rufus, § 2).'),
    (1029, "Bishop Palladius, *St. Pachomius the Great*, pp. 128, 125, 135, 75. These incidents are recounted only, however, in the Arabic recension of the *Life of St. Pachomius* according unto a 19th-century manuscript."),
    (1030, "*Apophthegmata Patrum*, Sisoes, § 39."),
    (1031, "*Apophthegmata Patrum*, Theodore of Pherme, § 3."),
    (1032, "*Ancient Patericon*, IX, 2."),
    (1033, "*Ancient Patericon*, IX, 1."),
    (1034, "*Apophthegmata Patrum*, Moses, § 2."),
    (1035, "*Ibid.*, Pior, § 3."),
    (1036, "*Ibid.*, Poemen, § 70."),
    (1037, "*Apophthegmata Patrum*, Macarius the Citizen (of Alexandria), § 2."),
    (1038, "It is characteristic that these two contemporary ascetics never once saw or spoke with one another."),
    (1039, "*Life of St. Pachomius* in the Greek recension, § 77, and Arabic, §§ 65, 69; Bishop Palladius, *St. Pachomius the Great*, p. 166. Concerning Aut no further information hath survived."),
    (1040, "Palladius, *Historia Lausiaca*, ch. 19."),
    (1041, "Cf. concerning St. Anthony, p. 200. In the Coptic and Greek recensions of the *Life of St. Pachomius* there is no mention of an Angel imparting a typikon, but only of an Angel appearing unto St. Pachomius when the venerable father still lived as an anchorite; whereupon the Angel said unto him: \"It is the will of God that thou serve the human race, reconciling it unto God\" (according unto the Greek, the Angel repeated this unto him thrice; according unto the Coptic, he called his name thrice). After this vision those wishing to struggle under his guidance began to gather unto St. Pachomius. Bishop Palladius, *St. Pachomius the Great*, p. 52."),
    (1042, "Palladius, *Historia Lausiaca*, ch. 38 (34); Sozomen, *Historia Ecclesiastica*, III, 14; *Life of St. Pachomius* translated by Dionysius Exiguus, ch. 22; Migne, *PL*, t. 73, cols. 242–243; Arabic *Life* in French translation by É. Amélineau in *Annales du Musée Guimet*, t. XVII, Paris, 1889, pp. 366–369."),
    (1043, 'Sozomen: "The rules permitted each to eat and drink, to work and to fast or not to fast, as much as each was able, and commanded that upon those who ate more the more difficult labors be laid, while upon the ascetics, lighter ones." Dionysius: "Permit each to eat and drink according unto his strength, and in proportion unto nourishment constrain him to labor; forbid neither moderate eating nor fasting; give the stronger and those who eat heavier labors, and the weaker and abstinent lighter ones." Arabic: "Permit each to eat and drink what shall be needful for him; hinder them not from fasting, but leave this unto their free choice, and give unto those strong in body heavy and burdensome labors, and unto those weak and pious, light and unburdensome ones." In the Arabic this rule standeth in the second place, while in the first place is that concerning cells (which followeth in the Greek *Lausiac History*).'),
    (1044, 'Sozomen: "to build many small dwellings." Dionysius: "make diverse cells." Arabic: "build many cells in thy monastery."'),
    (1045, 'Sozomen: "house." Arabic: "unite them at a single table for food."'),
    (1046, 'Sozomen: "enclosed on both sides." Arabic simply: "low seats." In Dionysius this entire rule is absent.'),
    (1047, 'Sozomen: "a leather garment." Arabic: "tanned skin, of sheep or goat."'),
    (1048, 'Arabic: "if they desire on Saturday or Sunday to receive the Holy Mysteries"; in Dionysius "on Saturday or Sunday" is absent.'),
    (1049, "Absent in the Arabic."),
    (1050, 'Sozomen: "woolen caps." Dionysius simply: "cowls (*cuculli*)." Arabic: "cowls resembling those worn by children who have done no evil"; according unto the Arabic they are put on seemingly only for the reception of the Eucharist.'),
    (1051, 'Absent in Dionysius and in the Arabic; in Sozomen: "to make upon the caps marks of purple color (*kentron*)."'),
    (1052, 'In Sozomen such practical application is not indicated, whereas in the Arabic another application is given: "that by means of the form of the letter assigned unto them they might examine their deeds, know their conduct, guard themselves against evil habits, and transfer themselves into the rank designated by the letter *iota*, with the assistance of their zeal and emulation in conduct."'),
    (1053, 'In Dionysius the letters *alpha*, *zeta*, *lambda*, *rho*, *sigma* are additionally adduced as examples, yet without indication of their significance. In the Arabic recension: "and as for the letter *rho*, beware of it and act in accordance with the sign that it representeth."'),
    (1054, 'Arabic: "The Angel instructed Pachomius how best to familiarize the spiritual fathers also with these signs."'),
    (1055, 'Sozomen: "Permit not a stranger to eat together with them, unless some traveler be received." Dionysius: "If a stranger should come from another monastery, having a different habit (*habitum*), let none eat with him, except one who, being on a journey, could not observe this (*observare*)." Arabic: "Receive not a brother coming from another monastery if he hath in general acquired habits not identical with thine; but receive strangers, comfort them, and show mercy unto the poor in a special place of thy monastery, so as not to eat or drink with them."'),
    (1056, 'Arabic adds: "tonsure the hair of his head."'),
    (1057, 'Dionysius: "*studiis sacratioribus*" ("unto more sacred pursuits").'),
    (1058, 'Dionysius: "let him perform only his labors." Arabic: "employ him in the affairs of the monastery."'),
    (1059, 'Sozomen: "to sit at table with covered faces, so as not to see one another or anything else except the table and the foods set before them."'),
    (1060, 'Sozomen: "to pray every day 12 times, and as many in the evening and as many at night, and at the ninth hour 3 times; moreover, prior unto taking food to preface prayer by the chanting of a psalm." Dionysius: "there shall be 12 day prayers (*diurnae orationes*), 12 evening prayers, and 12 night prayers." Arabic: "let each of the brethren make 12 prayers in the course of the day; and at the evening hour, when they assemble to take food, let each of them make three prayers before eating, and six before sleep, and with every prayer a psalm. Let them sleep half the night, and let them spend the other half keeping vigil, for the sake of unceasing prayer and the glorification of God."'),
    (1061, 'Arabic: "these prayers are not few for those who have spent but a little time in such a life, lest prayer become wearisome unto them."'),
    (1062, 'Dionysius: "remaining in their cells, they pray without ceasing." Arabic: "and I know that their days and nights shall be employed in accordance with the laws of God."'),
    (1063, "Let us recall this practice depicted on pp. 202–210 and we shall become convinced that each rule as it were lowereth its individual requirements by several degrees. From such a point of view the rule concerning sleep will likewise not appear petty (see I. Troitsky, *Review of Sources for the Primary History of Egyptian Monasticism* [*Obozrenie istochnikov nachal'noy istorii egipetskogo monashestva*], p. 62); in place of sleep in a standing or sitting posture, sleep in a semi-reclining posture is permitted. Most strange appeareth the rule concerning the division of the monks into classes according unto the number of the letters of the Greek alphabet. One may regard this rule as a distinctive poetic (with mystical coloring) representation of the pastoral care of the superior of the monastery for the brethren."),
    (1064, "See above, p. 139."),
    (1065, 'The Arabic recension of the typikon defineth the number of prayers only in place of the Liturgy with its Hours ("day prayers"), the 9th Hour ("before food"), and Vespers ("before sleep"), appointing for each service a number of prayers proportional unto its importance: 12, 6, 3; whereas the night office it defineth not by the quantity of prayers, but by their duration: half the night.'),
    (1066, "John Cassian, *Institutes* (*De Institutis Coenobiorum*), II, 7."),
    (1067, "See above, pp. 189 ff."),
    (1068, 'The not entirely clear expression concerning this latter "prayer" hath, probably, such a meaning: if the meal on a given day is not common, but separate for each "order" or class of monks, for each house of the monastery, then prior unto it there is chanted one psalm with prayer; whereas if it is common, for several orders (houses), then as many psalms with prayer are chanted as there are of these "orders" participating in the meal. Thus the meal was prefaced by an office in composition not different from other offices; cf. among us the Order of the Panagia; see the explanation of Chapter 2 of the Typikon, end.'),
    (1069, 'See below: "Divine Worship in Egyptian Cenobia According unto Cassian."'),
    (1070, "See above, p. 201."),
    (1071, "See above, p. 189."),
    (1072, 'Even if the tradition in all its particulars may arouse and hath indeed aroused doubt even among Russian scholars (Bishop Palladius, *St. Pachomius the Great*, pp. 56 ff.; I. Troitsky, *Review of Sources for the History of Egyptian Monasticism*, pp. 62 ff.), nonetheless the *Lives* of St. Pachomius insistently testify that the venerable father left in general a written typikon, as for example the Arabic *Life*: "Pachomius gave them laws and commandments, whereof some were written down, while others were communicated by his mouth; he commanded the brethren that if anyone violate one appointed rule, he receiveth the punishment determined for disobedience." É. Amélineau in *Annales du Musée Guimet*, t. XVII, p. 502.'),
    (1073, "Migne, *PL*, t. 23, col. 62."),
    (1074, "Bishop Palladius, *St. Pachomius the Great*, p. 31."),
    (1075, "Placed in Migne, *PL*, t. 50, at the end of the works of St. John Cassian."),
    (1076, "Placed in J. Bollandus, *Acta Sanctorum Maii*, t. 3, at the end of the *Lives of Saints Pachomius and Theodore the Consecrated*; with this recension of the rules the Ethiopic version in A. Dillmann, *Chrestomathia Aethiopica*, Leipzig, 1855, pp. 57–69, coincideth."),
    (1077, "We make use of the systematic review thereof in Bishop Theophan (the Recluse), *Ancient Monastic Typika of St. Pachomius the Great, St. Basil the Great, St. John Cassian, and St. Benedict* (*Drevnie inocheskie ustavy*), Moscow, 1892, pp. 90–154."),
    (1078, "Concerning him Abba Orsisius (Horsiesius) saith in his *Teaching on the Institution of Monks*: \"And you, second in command (*vtorstvuyushchie*) in the monasteries, show yourselves to be first in virtue\" (§ 14; Migne, *PG*, t. 40). In later monasteries this office corresponded unto the *kathegumenos* (*kathēgoumenos*) or the ecclesiarch (*ekklēsiarchēs*).")
]

# Write files
ws = Path("Liturgical Monuments/Monument 6 - 1910 Skaballanovich Typikon")

source_file = ws / "Source Text" / "1910_skaballanovich_typikon_cohort20_source.txt"
draft_file = ws / "Draft" / "1910_skaballanovich_typikon_cohort20_raw_draft.md"
fn_file = ws / "Draft" / "1910_skaballanovich_typikon_cohort20_footnotes.txt"

source_content = "\n\n".join(source_leaves[p] for p in range(191, 201)) + "\n"
draft_content = "\n\n".join(draft_leaves[p] for p in range(191, 201)) + "\n"
fn_content = "\n".join(f"[^{num}]: {text}" for num, text in footnotes_list) + "\n"

source_file.write_text(source_content, encoding="utf-8")
print(f"Wrote source file: {source_file}, size: {source_file.stat().st_size} bytes")

draft_file.write_text(draft_content, encoding="utf-8")
print(f"Wrote draft file: {draft_file}, size: {draft_file.stat().st_size} bytes")

fn_file.write_text(fn_content, encoding="utf-8")
print(f"Wrote footnotes file: {fn_file}, size: {fn_file.stat().st_size} bytes")
