import sys
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')

DRAFT_TEXT = """=== LEAF p441 ===

# Month of March: The Holy Forty Martyrs (Situations VI Concl., VII § 12, VIII § 13)

## Τῇ Θ΄: Τῶν Ἁγίων Μ΄ Μαρτύρων (Περιπτώσεις Ϛ΄ Τέλος, Ζ΄ § 12, Η΄ § 13) [Violakis, p. 426]

    Τῇ Δευτέρᾳ πρωῒ ἡ Ἀκολουθία τοῦ Ὄρθρου, αἱ Ὧραι καὶ ἡ Λειτουργία τῶν Προηγιασμένων, ψάλλονται ὡς διετάχθησαν ἐν τῇ Α΄ περιπτώσει § 2, 3.
    Εἰ δὲ τύχοι τῇ Τρίτῃ τῆς Β΄, Γ΄, Δ΄ καὶ Ε΄ ἑβδομάδος, ἐν τῷ Ἑσπερινῷ τῆς Προηγιασμένης, τὸ Ἰδιόμελον τῶν Ἀποστίχων τῆς ἡμέρας δίς, τὸ Μαρτυρικὸν ἅπαξ, τὰ γ΄ τῆς σειρᾶς Προσόμοια καὶ δ΄ τῶν Ἁγίων, Δόξα, τῶν Ἁγίων, Καὶ νῦν, Προσόμοιον Σταυροθεοτοκίον κτλ. ὡς ἐν περιπτώσει Α΄ § 2, 3.

### Ζ΄.

12.    Εἰ τύχοι τῇ Τετάρτῃ τῆς Δ΄ ἑβδομάδος, τὸ πρωῒ ἡ Ἀκολουθία τοῦ Ὄρθρου ψάλλεται ὡς διετάχθη ἐν περιπτώσει Α΄ § 2, 3, αἱ δὲ Ὧραι ἀναγινώσκονται λιταὶ καὶ λέγομεν ἀντὶ τοῦ Τὸ πρωῒ εἰσάκουσον τῆς φωνῆς μου καὶ Κύριε ὁ τὸ Πανάγιόν σου κτλ. Τὸν Σταυρόν σου Προσκυνοῦμεν Δέσποτα. Ἀπολυτίκιον Τὰς ἀλγηδόνας τῶν Ἁγίων, καὶ Κοντάκιον Οὐκέτι φλογίνη ῥομφαία. Ἐν δὲ τῷ Ἑσπερινῷ μετὰ τὸν Προοιμιακὸν καὶ τὰ Πρὸς Κύριον, εἰς τὸ Κύριε ἐκέκραξα τὰ δύο Ἰδιόμελα καὶ τὸ Μαρτυρικόν, τοῦ Τριῳδίου γ΄ Προσόμοια, καὶ τῶν Ἁγίων δ΄, Δόξα, Τὴν λίμνην ὡς παράδεισον, Καὶ νῦν, Σήμερον ὁ ἀπρόσιτος τῇ οὐσίᾳ, Εἴσοδος μετὰ τοῦ Εὐαγγελίου, Φῶς ἱλαρόν, καὶ τὰ Ἀναγνώσματα τῆς ἡμέρας, τὸ Κατευθυνθήτω, Ἀπόστολος καὶ Εὐαγγέλιον τῶν Μαρτύρων, καὶ καθεξῆς ἡ Λειτουργία τῶν Προηγιασμένων, Κοινωνικὸν Εἰς μνημόσυνον, Εὐλογήσω τὸν Κύριον καὶ Ἀπόλυσις.

### Η΄.

13.    Εἰ τύχοι ἐν Σαββάτῳ τῆς Β΄, Γ΄ καὶ Δ΄ ἑβδομάδος: τῇ Παρασκευῇ πρωῒ εἰς τὸν Ἑσπερινόν, μετὰ τὸν Προοιμιακὸν καὶ τὰ Πρὸς Κύριον, εἰς τὸ Κύριε ἐκέκραξα ψάλλομεν τὸ Ἰδιόμελον τῆς ἡμέρας δίς, δ΄ Μαρτυρικὰ τοῦ τυχόντος ἤχου καὶ δ΄ τῶν Ἁγίων, Δόξα, Ἐν ᾠδαῖς ᾀσμάτων, Καὶ νῦν, τὸ α΄ Θεοτοκίον τοῦ ἤχου. Εἴσοδος μετὰ θυμιατοῦ, Φῶς ἱλαρόν, καὶ τὰ Ἀναγνώσματα τῆς ἡμέρας, τὸ Κατευθυνθήτω, καὶ καθεξῆς ἡ Λειτουργία τῶν Προηγιασμένων, Κοινωνικὸν Γεύσασθε καὶ ἴδετε, Εὐλογήσω τὸν Κύριον, καὶ Ἀπόλυσις. Τὸ ἑσπέρας ἀναγινώσκονται οἱ Οἶκοι τῆς Θεοτόκου ὡς εἴθισται.

=== LEAF p442 ===

# Month of March: The Holy Forty Martyrs (Situations VI Concl., VII § 12, VIII § 13)

## March 9: The Holy Forty Martyrs [in the Lake of Sebastea] (Situations VI Concl., VII § 12, VIII § 13) [Violakis, p. 427]

    On Monday morning the Service of Matins, the Hours and the Liturgy of the Presanctified Gifts are chanted as prescribed in Situation One, Paragraphs 2 and 3.
    If the Feast occurs on Tuesday of the 2nd, 3rd, 4th, or 5th Week: in the Vespers of the Presanctified, the Idiomelon of the Aposticha of the day twice, the Martyrikon once, the 3 Prosomia of the sequence, and 4 of the Saints; "Glory...": of the Saints; "Both now and ever...": Prosomion Stavrotheotokion, etc., as in Situation One, Paragraphs 2 and 3.

### SITUATION SEVEN

12.    If the Feast occurs on Wednesday of the 4th Week [Mid-Lent Wednesday]: in the morning the Service of Matins is sung as prescribed in Situation One, Paragraphs 2 and 3; the Hours are read plainly, and instead of **"In the morning hear my voice"** and **"O Lord, Who at the third hour didst send down Thy Most Holy Spirit..."** etc., we say: **"Thy Cross do we adore, O Master"** (*Τὸν Σταυρόν σου Προσκυνοῦμεν Δέσποτα*). Dismissal Troparion: **"By reason of the sufferings which the Saints endured for Thy sake, O Lord"** (*Τὰς ἀλγηδόνας τῶν Ἁγίων*); and Kontakion: **"No longer doth the flaming sword"** (*Οὐκέτι φλογίνη ῥομφαία*). In Vespers, after the Introductory Psalm [Ps. 103 LXX] and "Unto the Lord" [Kathisma 18, Pss. 119–133 LXX], at "Lord, I have cried": the two Idiomela and the Martyrikon, the 3 Prosomia of the Triodion, and 4 of the Saints; "Glory...": **"The lake as paradise"** (*Τὴν λίμνην ὡς παράδεισον*); "Both now and ever...": **"Today He Who is unapproachable in essence"** (*Σήμερον ὁ ἀπρόσιτος τῇ οὐσίᾳ*); Entrance with the Holy Gospel Book, "O Gladsome Light", and the Readings of the day; **"Let my prayer arise"** [Ps. 140:2 LXX], the Epistle and Gospel of the Martyrs, and then the Liturgy of the Presanctified Gifts follows in due order; Communion Verse: **"In everlasting remembrance shall the righteous be"** (*Εἰς μνημόσυνον*, Ps. 111:6 LXX); **"I will bless the Lord at all times"** (*Εὐλογήσω τὸν Κύριον*, Ps. 33:2 LXX), and Dismissal.

### SITUATION EIGHT

13.    If the Feast occurs on Saturday of the 2nd, 3rd, or 4th Week: on Friday morning at Vespers, after the Introductory Psalm [Ps. 103 LXX] and "Unto the Lord" [Kathisma 18, Pss. 119–133 LXX], at "Lord, I have cried", we sing the Idiomelon of the day twice, 4 Martyrika in the Tone occurring, and 4 of the Saints; "Glory...": **"In songs and hymns let us praise"** (*Ἐν ᾠδαῖς ᾀσμάτων*); "Both now and ever...": the first Theotokion of the Tone; Entrance with the censer, "O Gladsome Light", and the Readings of the day; **"Let my prayer arise"** [Ps. 140:2 LXX], and then the Liturgy of the Presanctified Gifts follows in due order; Communion Verse: **"O taste and see"** (*Γεύσασθε καὶ ἴδετε*, Ps. 33:9 LXX); **"I will bless the Lord at all times"** (*Εὐλογήσω τὸν Κύριον*, Ps. 33:2 LXX), and Dismissal. In the evening, the Oikoi of the Theotokos [Akathist Stasis] are read as customary, with the Kontakion: **"Every army"** (*Πᾶσαν στρατιάν*).[^280]

=== LEAF p443 ===

# Month of March: The Holy Forty Martyrs (Situations VIII Concl. § 13, IX § 14, X § 15)

## Τῇ Θ΄: Τῶν Ἁγίων Μ΄ Μαρτύρων (Περιπτώσεις Η΄ Τέλος § 13, Θ΄ § 14, Ι΄ § 15) [Violakis, p. 428]

    Κοντάκιον Πᾶσαν στρατιάν.
    Τῷ Σαββάτῳ πρωῒ ἡ Ἀκολουθία τοῦ Ὄρθρου μετὰ τῆς Λειτουργίας τοῦ Χρυσοστόμου ψάλλονται κατὰ τὴν γνωστὴν διάταξιν. Ἀπόστολος καὶ Εὐαγγέλιον τῶν Ἁγίων. Κοινωνικὸν Εἰς μνημόσυνον.

### Θ΄.

14.    Εἰ τύχοι τῇ Τετάρτῃ τῆς Ε΄ ἑβδομάδος, τὸ πρωῒ ἡ Ἀκολουθία τοῦ Ὄρθρου καὶ τῶν Ὡρῶν ψάλλεται ὡς διετάχθη ἐν περιπτώσει Α΄ § 2. Ἐν δὲ τῷ Ἑσπερινῷ, μετὰ τὸν Προοιμιακὸν καὶ τὰ Πρὸς Κύριον, εἰς τὸ Κύριε ἐκέκραξα ἀρχόμεθα ἀπὸ τοῦ Στίχου Πεσοῦνται ἐν ἀμφιβλήστρῳ αὐτῶν οἱ ἁμαρτωλοί, καὶ ψάλλομεν τὸ Ἰδιόμελον τῆς ἡμέρας δίς, καὶ τὸ Μαρτυρικόν, εἶτα τὰ γ΄ τῆς σειρᾶς τοῦ Τριῳδίου Προσόμοια, καὶ δ΄ τῶν Ἁγίων Φέροντες τὰ παρόντα γενναίως, καὶ ἀκολούθως κατ᾿ ἀλφάβητον Στιχηρὰ τοῦ Τριῳδίου Ἅπας ὁ βίος μου, μέχρι τοῦ Στιχηροῦ Ὢ τῆς ἀφάτου σου εὐσπλαγχνίας· Δόξα, τῶν Ἁγίων, Τὴν λίμνην ὡς παράδεισον, Καὶ νῦν, Ἔργοις σκοτεινοῖς συναπαχθείς. Εἴσοδος μετὰ τοῦ Εὐαγγελίου, Φῶς ἱλαρόν, καὶ τὰ Ἀναγνώσματα τῆς ἡμέρας, τὸ Κατευθυνθήτω, Ἀπόστολος καὶ Εὐαγγέλιον τῶν Ἁγίων, καὶ καθεξῆς ἡ Λειτουργία τῶν Προηγιασμένων, Κοινωνικὸν Εἰς μνημόσυνον, Εὐλογήσω τὸν Κύριον καὶ Ἀπόλυσις.
    Τὸ ἑσπέρας ψάλλεται ὁ Μ. Κανών, ὡς εἴθισται, μετὰ μικροῦ Ἀποδείπνου.

### Ι΄.

15.    Εἰ τύχοι τῇ Πέμπτῃ τοῦ Μεγάλου Κανόνος, τῇ Τετάρτῃ πρωῒ ὁ Ἑσπερινὸς καὶ ἡ Λειτουργία ψάλλονται ὡς ἐν περιπτώσει Θ΄ § 14· ἀλλὰ Ἀπόστολος καὶ Εὐαγγέλιον, ὡς καὶ τὸ Δοξαστικόν, οὐ λέγονται, Κοινωνικὸν δὲ τὸ Γεύσασθε. Τῇ Πέμπτῃ πρωΐ, μετὰ τὸν Ν΄ ψαλμόν, τὸ Τρισάγιον, τὸ Ἀπολυτίκιον τῶν Ἁγίων καὶ ὁ Ἑξάψαλμος. Εἰς τὸ Θεὸς Κύριος, τὸ Ἀπολυτίκιον τῶν Ἁγίων δίς, καὶ τὸ Θεοτοκίον· εἶτα τὸ Ψαλτήριον, τὰ Καθίσματα τῶν Ἁγίων μετὰ τῶν Θεοτοκίων αὐτῶν, ὁ Ν΄ ψαλμὸς χῦμα, καὶ ἀναγινώσκεται ἡ α΄ καὶ γ΄ Ὠδὴ τοῦ Κανόνος τῶν Ἁγίων ὡς καὶ τὸ μετὰ τὴν Αἴτησιν Κάθισμα τῶν Ἁγίων καὶ τὸ Θεοτοκίον· εἶτα ἡ δ΄ Ὠδὴ τοῦ Τριῳδίου καὶ ἡ τῶν Ἁγίων, ἡ ε΄ καὶ ἡ ς΄ Ὠδὴ τῶν Ἁγίων καὶ ἡ Αἴτησις, τὸ Κοντάκιον Ψυχή μου ψυχή μου καὶ τὸ Μηνολόγιον τῶν Μαρτύρων, εἶτα (ἡ ζ΄ ᾠδὴ

=== LEAF p444 ===

# Month of March: The Holy Forty Martyrs (Situations VIII Concl. § 13, IX § 14, X § 15)

## March 9: The Holy Forty Martyrs [in the Lake of Sebastea] (Situations VIII Concl. § 13, IX § 14, X § 15) [Violakis, p. 429]

    Kontakion: **"Every army"** (*Πᾶσαν στρατιάν*).
    On Saturday morning, the Service of Matins with the Liturgy of Saint John Chrysostom are sung according to the known order; Epistle and Gospel of the Saints; Communion Verse: **"In everlasting remembrance shall the righteous be"** (*Εἰς μνημόσυνον*, Ps. 111:6 LXX).

### SITUATION NINE

14.    If the Feast occurs on Wednesday of the 5th Week: in the morning, the Service of Matins and the Hours are sung as prescribed in Situation One, Paragraph 2. At Vespers, after the Introductory Psalm [Ps. 103 LXX] and "Unto the Lord" [Kathisma 18, Pss. 119–133 LXX], at "Lord, I have cried", we begin from the Verse: **"The sinners shall fall into their net"** [Ps. 140:10 LXX], and we sing the Idiomelon of the day twice, and the Martyrikon; then the 3 Prosomia of the sequence of the Triodion, and 4 of the Saints: **"Bravely enduring the sufferings of the present life"** (*Φέροντες τὰ παρόντα γενναίως*); and following these, the alphabetical Stichira of the Triodion: **"All my life"** (*Ἅπας ὁ βίος μου*), until the Stichiron: **"O Thine ineffable loving-kindness"** (*Ὢ τῆς ἀφάτου σου εὐσπλαγχνίας*); "Glory...": of the Saints: **"The lake as paradise"** (*Τὴν λίμνην ὡς παράδεισον*); "Both now and ever...": **"Led away by works of darkness"** (*Ἔργοις σκοτεινοῖς συναπαχθείς*); Entrance with the Holy Gospel Book, "O Gladsome Light", and the Readings of the day; **"Let my prayer arise"** [Ps. 140:2 LXX], the Epistle and Gospel of the Saints, and then the Liturgy of the Presanctified Gifts follows in due order; Communion Verse: **"In everlasting remembrance shall the righteous be"** (*Εἰς μνημόσυνον*, Ps. 111:6 LXX); **"I will bless the Lord at all times"** (*Εὐλογήσω τὸν Κύριον*, Ps. 33:2 LXX), and Dismissal.
    In the evening, the Great Canon is chanted, as customary, with the Small Compline.

### SITUATION TEN

15.    If the Feast occurs on Thursday of the Great Canon: on Wednesday morning, Vespers and the Liturgy are sung as in Situation Nine, Paragraph 14; but the Epistle and Gospel, as well as the Doxastikon, are not said; Communion Verse: **"O taste and see"** (*Γεύσασθε καὶ ἴδετε*, Ps. 33:9 LXX). On Thursday morning, after Psalm 50 [LXX], the Trisagion Prayers, the Dismissal Troparion of the Saints, and the Hexapsalmos. At "God is the Lord": the Dismissal Troparion of the Saints twice, and the Theotokion; then the Psalter, the Kathismata of the Saints with their Theotokia, Psalm 50 read plainly; and the 1st and 3rd Odes of the Canon of the Saints are read, as well as the Kathisma of the Saints and the Theotokion which follow the Little Litany; then the 4th Ode of the Triodion and that of the Saints; then the 5th and 6th Odes of the Saints and the Little Litany, the Kontakion: **"My soul, my soul, arise"** (*Ψυχή μου ψυχή μου*) and the Menologion of the Martyrs; then [the 7th Ode, which is omitted here, perhaps due to a typographical error][^281]

=== LEAF p445 ===

# Month of March: The Holy Forty Martyrs (Situations X Concl. §§ 15–16, XI §§ 17–18)

## Τῇ Θ΄: Τῶν Ἁγίων Μ΄ Μαρτύρων (Περιπτώσεις Ι΄ Τέλος §§ 15–16, ΙΑ΄ §§ 17–18) [Violakis, p. 430]

μὴ ἀναφερομένη ἐδῶ πιθανὸν ἕνεκα τυπογραφικῆς παραλείψεως,) ἡ η΄ καὶ θ΄ Ὠδὴ τοῦ Τριῳδίου, ὡς καὶ ἡ τῶν Ἁγίων, Καταβασίαι Ἀνοίξω τὸ στόμα μου καὶ μετὰ Τὴν τιμιωτέραν τὸ Ἐξαποστειλάριον τῶν Ἁγίων καὶ τὸ Θεοτοκίον. Εἰς τοὺς Αἴνους τὰ Προσόμοια Δεῦτε μαρτυρικὴν ἀδελφοί, Δόξα, Ἀθλοφόροι Χριστοῦ, Καὶ νῦν, Μακαρίζομέν σε. Δοξολογία Μεγάλη, τὸ Ἀπολυτίκιον τῶν Μαρτύρων, καὶ ἀναγινώσκονται αἱ Ὧραι, ἐν αἷς λέγομεν Ἀπολυτίκιον Τὰς ἀλγηδόνας τῶν Ἁγίων, καὶ Κοντάκιον Ψυχή μου ψυχή μου. Εἰς τὴν Θ΄ Ὥραν ψάλλονται οἱ Μακαρισμοὶ καὶ τὰ λοιπὰ ὡς διετάχθησαν ἐν τῇ τοῦ ἁγίου Χαραλάμπους ἑορτῇ ἐν περιπτώσει Η΄ § 14 καὶ Ἀπόλυσις.

16.    Ἐν τῷ Ἑσπερινῷ, μετὰ τὸν Προοιμιακὸν καὶ τὰ Πρὸς Κύριον, εἰς τὸ Κύριε ἐκέκραξα ψάλλομεν τὸ Ἰδιόμελον Αὐτεξουσίως ἐξεδόθην δίς, καὶ τὸ Μαρτυρικόν, τὰ γ΄ Προσόμοια τοῦ Τριῳδίου καὶ δ΄ τῶν Ἁγίων, Δόξα, Ἐν ᾠδαῖς ᾀσμάτων, Καὶ νῦν, Σταυροθεοτοκίον Προσόμοιον, Εἴσοδος μετὰ τοῦ Εὐαγγελίου, Φῶς ἱλαρόν, καὶ τὰ Ἀναγνώσματα τῆς ἡμέρας, τὸ Κατευθυνθήτω, Ἀπόστολος καὶ Εὐαγγέλιον τῶν Ἁγίων καὶ καθεξῆς ἡ Λειτουργία τῶν Προηγιασμένων, Κοινωνικὸν Εἰς μνημόσυνον, Εὐλογήσω τὸν Κύριον καὶ Ἀπόλυσις.

### ΙΑ΄.

17.    Εἰ τύχοι τῇ Παρασκευῇ τῆς αὐτῆς ἑβδομάδος, τῇ Πέμπτῃ πρωῒ εἰς τὸν Ἑσπερινόν, μετὰ τὸ Ἰδιόμελον τὸ Μαρτυρικὸν καὶ τὰ γ΄ τῆς σειρᾶς Προσόμοια, καὶ δ΄ τῶν Μαρτύρων, Δόξα, Καὶ νῦν, Προσόμοιον Σταυροθεοτοκίον κτλ. Τῇ Παρασκευῇ πρωΐ, ἡ Ἀκολουθία τοῦ Ὄρθρου μετὰ τῶν Ὡρῶν ψάλλεται ὡς διετάχθη ἐν περιπτώσει Α΄ § 2.
18.    Ἐν τῷ Ἑσπερινῷ, μετὰ τὸν Προοιμιακὸν καὶ τὰ Πρὸς Κύριον, εἰς τὸ Κύριε ἐκέκραξα τὸ Ἰδιόμελον Ὡς ἐξ Ἱερουσαλὴμ δίς, δ΄ Προσόμοια τῆς Θεοτόκου Βουλὴν προαιώνιον, καὶ δ΄ τῶν Ἁγίων· Δόξα, Τὴν λίμνην ὡς παράδεισον, Καὶ νῦν, Τὸ ἀπ᾿ αἰῶνος μυστήριον. Εἴσοδος μετὰ τοῦ Εὐαγγελίου, Φῶς ἱλαρόν, καὶ τὰ Ἀναγνώσματα τῆς ἡμέρας, τὸ Κατευθυνθήτω, Ἀπόστολος καὶ Εὐαγγέλιον τῶν Ἁγίων καὶ καθεξῆς ἡ Λειτουργία τῶν Προηγιασμένων. Κοινωνικὸν Εἰς μνημόσυνον, Εὐλογήσω τὸν Κύριον καὶ Ἀπόλυσις.

=== LEAF p446 ===

# Month of March: The Holy Forty Martyrs (Situations X Concl. §§ 15–16, XI §§ 17–18)

## March 9: The Holy Forty Martyrs [in the Lake of Sebastea] (Situations X Concl. §§ 15–16, XI §§ 17–18) [Violakis, p. 431]

omission,] the 8th and 9th Odes of the Triodion as well as that of the Saints; Katavasiai: **"I shall open my mouth"** (*Ἀνοίξω τὸ στόμα μου*); and after "More honorable than the Cherubim", the Exapostilarion of the Saints and the Theotokion. At the Praises: the Prosomia: **"Come, O brethren, let us praise in song the band of martyrs"** (*Δεῦτε μαρτυρικὴν ἀδελφοί*); "Glory...": **"O prize-bearing martyrs of Christ"** (*Ἀθλοφόροι Χριστοῦ*); "Both now and ever...": **"We bless thee, O Virgin Theotokos"** (*Μακαρίζομέν σε*); Great Doxology; the Dismissal Troparion of the Martyrs; and the Hours are read, in which we say the Dismissal Troparion: **"By reason of the sufferings which the Saints endured for Thy sake, O Lord"** (*Τὰς ἀλγηδόνας τῶν Ἁγίων*), and the Kontakion: **"My soul, my soul, arise"** (*Ψυχή μου ψυχή μου*). At the 9th Hour, the Beatitudes are chanted and the rest of the order as prescribed in the Feast of Saint Charalampos, Situation Eight, Paragraph 14, and Dismissal.
16.    In Vespers, after the Introductory Psalm [Ps. 103 LXX] and "Unto the Lord" [Kathisma 18, Pss. 119–133 LXX], at "Lord, I have cried", we sing the Idiomelon: **"Of my own free will"** (*Αὐτεξουσίως ἐξεδόθην*) twice, and the Martyrikon; the 3 Prosomia of the Triodion, and 4 of the Saints; "Glory...": **"In songs and hymns let us praise"** (*Ἐν ᾠδαῖς ᾀσμάτων*); "Both now and ever...": the Prosomion Stavrotheotokion; Entrance with the Holy Gospel Book, "O Gladsome Light", and the Readings of the day; **"Let my prayer arise"** [Ps. 140:2 LXX], the Epistle and Gospel of the Saints, and then the Liturgy of the Presanctified Gifts follows in due order; Communion Verse: **"In everlasting remembrance shall the righteous be"** (*Εἰς μνημόσυνον*, Ps. 111:6 LXX); **"I will bless the Lord at all times"** (*Εὐλογήσω τὸν Κύριον*, Ps. 33:2 LXX), and Dismissal.

### SITUATION ELEVEN

17.    If the Feast occurs on Friday of the same week: on Thursday morning at Vespers, after the Idiomelon, the Martyrikon, the 3 Prosomia of the sequence, and 4 of the Martyrs; "Glory... Both now and ever...": Prosomion Stavrotheotokion, etc. On Friday morning, the Service of Matins with the Hours is chanted as prescribed in Situation One, Paragraph 2.
18.    In Vespers, after the Introductory Psalm [Ps. 103 LXX] and "Unto the Lord" [Kathisma 18, Pss. 119–133 LXX], at "Lord, I have cried": the Idiomelon **"As from Jerusalem"** (*Ὡς ἐξ Ἱερουσαλὴμ*) twice, 4 Prosomia of the Theotokos: **"Revealing to thee the pre-eternal counsel"** (*Βουλὴν προαιώνιον*), and 4 of the Saints; "Glory...": **"The lake as paradise"** (*Τὴν λίμνην ὡς παράδεισον*); "Both now and ever...": **"The mystery which was hidden from all eternity"** (*Τὸ ἀπ᾿ αἰῶνος μυστήριον*); Entrance with the Holy Gospel Book, "O Gladsome Light", and the Readings of the day; **"Let my prayer arise"** [Ps. 140:2 LXX], the Epistle and Gospel of the Saints, and then the Liturgy of the Presanctified Gifts follows in due order; Communion Verse: **"In everlasting remembrance shall the righteous be"** (*Εἰς μνημόσυνον*, Ps. 111:6 LXX); **"I will bless the Lord at all times"** (*Εὐλογήσω τὸν Κύριον*, Ps. 33:2 LXX), and Dismissal.[^282]

=== LEAF p447 ===

# Month of March: The Holy Forty Martyrs (Situations XI Concl., XII §§ 19–21)

## Τῇ Θ΄: Τῶν Ἁγίων Μ΄ Μαρτύρων (Περιπτώσεις ΙΑ΄ Τέλος, ΙΒ΄ §§ 19–21) [Violakis, p. 432]

    Τὸ ἑσπέρας ψάλλεται ὁ Ἀκάθιστος Ὕμνος μετὰ Μικροῦ Ἀποδείπνου, ὡς εἴθισται· Κοντάκιον Τῇ ὑπερμάχῳ.

### ΙΒ΄.

19.    Εἰ τύχοι τῷ Σαββάτῳ τοῦ Ἀκαθίστου, τῇ Παρασκευῇ πρωῒ ἐν τῷ Ἑσπερινῷ, μετὰ τὸν Προοιμιακὸν καὶ τὰ Πρὸς Κύριον, εἰς τὸ Κύριε ἐκέκραξα ψάλλομεν τὸ Ἰδιόμελον Ὡς ἐξ Ἱερουσαλὴμ δίς, δ΄ Προσόμοια τῆς Θεοτόκου Βουλὴν προαιώνιον, καὶ δ΄ τῶν Μαρτύρων· Δόξα, Προφητικῶς ἀνεβόα, Καὶ νῦν, Τὸ ἀπ᾿ αἰῶνος μυστήριον. Εἴσοδος μετὰ θυμιατοῦ, Φῶς ἱλαρόν, καὶ τὰ Ἀναγνώσματα τῆς ἡμέρας, τὸ Κατευθυνθήτω, καὶ καθεξῆς ἡ Λειτουργία τῶν Προηγιασμένων, Κοινωνικὸν Γεύσασθε καὶ ἴδετε, Εὐλογήσω τὸν Κύριον, καὶ Ἀπόλυσις.
    Τὸ ἑσπέρας ψάλλεται ὁ Ἀκάθιστος Ὕμνος μετὰ μικροῦ Ἀποδείπνου, ὡς εἴθισται· Κοντάκιον Τῇ ὑπερμάχῳ.
20.    Τῷ Σαββάτῳ εἰς τὸν Ὄρθρον, μετὰ τὸ Μεσονυκτικόν, τὸ Τρισάγιον, Τὸ προσταχθὲν μυστικῶς, καὶ ὁ Ἑξάψαλμος. Εἰς τὸ Θεὸς Κύριος, Τὸ προσταχθὲν μυστικῶς, Τὰς ἀλγηδόνας τῶν Ἁγίων, καὶ αὖθις Τό προσταχθὲν· εἶτα τὸ Ψαλτήριον, τὰ Καθίσματα τῶν Ἁγίων Τὸ σεπτὸν στερέωμα (ζήτει ἀπὸ γ΄ Ὠδῆς)[Αὐτὰ ὅμως τὰ Καθίσματα ἀνήκουν εἰς τὴν πρώτην Στάσιν τοῦ Ὄρθρου τῆς 9 Μαρτίου, κατὰ τὸ Μηναῖον.] Δόξα, Καὶ νῦν, Ὁ μέγας στρατηγός· εἰς τὴν β΄ στιχολογίαν, τῶν Ἁγίων Τῷ Χριστῷ στρατευθέντες, Δόξα, Καὶ νῦν, Ἐνθυμοῦμαι τὴν κρίσιν, [τὰ παρόντα Καθίσματα τῆς δευτέρας Στάσεως ἀκολουθοῦν τὴν γ΄ Ὠδήν] καὶ εὐθὺς ὁ Ν΄ ψαλμὸς χῦμα. Κανόνες ὁ τῆς Θεοτόκου Ἀνοίξω τὸ στόμα μου, καὶ ὁ τῶν Ἁγίων· ἀπὸ γ΄ Ὠδῆς τὸ Κάθισμα Ὁ μέγας στρατηγὸς ἅπαξ· ἀφ᾿ ς΄ τὸ Κοντάκιον Τῇ ὑπερμάχῳ, καὶ ὁ Οἶκος Ἄγγελος πρωτοστάτης, τὸ Μηνολόγιον τῶν Μαρτύρων καὶ τὸ Ὑπόμνημα τοῦ Τριῳδίου, αἱ Καταβασίαι Ἀνοίξω τὸ στόμα μου, καὶ στιχολογοῦμεν Τὴν τιμιωτέραν. Ἐξαποστειλάρια τῶν Ἁγίων, καὶ τὸ τοῦ Τριῳδίου Τὸ ἀπ᾿ αἰῶνος σήμερον. Εἰς τοὺς Αἴνους, τῆς Θεοτόκου Προσόμοια Κεκρυμμένον μυστήριον γ΄ καὶ γ΄ τῶν Ἁγίων Δεῦτε μαρτυρικὴν ἀδελφοί, Δόξα, Ἀθλοφόροι Χριστοῦ, Καὶ νῦν, Γλῶσσαν [ἣν] οὐκ ἔγνω. Δοξολογία Μεγάλη καὶ τὸ Ἀπολυτίκιον Τὰς ἀλγηδόνας τῶν Ἁγίων.
21.    Εἰς τὴν Λειτουργίαν, τὰ Τυπικὰ καὶ οἱ Μακαρισμοὶ

=== LEAF p448 ===

# Month of March: The Holy Forty Martyrs (Situations XI Concl., XII §§ 19–20)

## March 9: The Holy Forty Martyrs [in the Lake of Sebastea] (Situations XI Concl., XII §§ 19–20) [Violakis, p. 433]

    In the evening, the Akathist Hymn is sung with the Small Compline, as customary; Kontakion: **"To thee, the Champion Leader"** (*Τῇ ὑπερμάχῳ*).

### SITUATION TWELVE

19.    If the Feast occurs on the Saturday of the Akathist: on Friday morning at Vespers, after the Introductory Psalm [Ps. 103 LXX] and "Unto the Lord" [Kathisma 18, Pss. 119–133 LXX], at "Lord, I have cried", we chant the Idiomelon: **"As from Jerusalem"** (*Ὡς ἐξ Ἱερουσαλὴμ*) twice, 4 Prosomia of the Theotokos: **"Revealing to thee the pre-eternal counsel"** (*Βουλὴν προαιώνιον*), and 4 of the Martyrs; "Glory...": **"David cried out prophetically in the psalms"** (*Προφητικῶς ἀνεβόα*); "Both now and ever...": **"The mystery which was hidden from all eternity"** (*Τὸ ἀπ᾿ αἰῶνος μυστήριον*); Entrance with the censer, "O Gladsome Light", and the Readings of the day; **"Let my prayer arise"** [Ps. 140:2 LXX], and then the Liturgy of the Presanctified Gifts follows in due order; Communion Verse: **"O taste and see"** (*Γεύσασθε καὶ ἴδετε*, Ps. 33:9 LXX); **"I will bless the Lord at all times"** (*Εὐλογήσω τὸν Κύριον*, Ps. 33:2 LXX), and Dismissal.
    In the evening, the Akathist Hymn is sung with the Small Compline, as customary; Kontakion: **"To thee, the Champion Leader"** (*Τῇ ὑπερμάχῳ*).
20.    On Saturday at Matins: after the Midnight Service, the Trisagion Prayers, **"Taking knowledge of the secret command"** (*Τὸ προσταχθὲν μυστικῶς*), and the Hexapsalmos. At "God is the Lord": **"Taking knowledge of the secret command"**, the Dismissal Troparion of the Saints: **"By reason of the sufferings which the Saints endured for Thy sake, O Lord"** (*Τὰς ἀλγηδόνας τῶν Ἁγίων*), and once again **"Taking knowledge of the secret command"**; then the Psalter; the Kathismata of the Saints: **"The venerable firmament"** (*Τὸ σεπτὸν στερέωμα*) (seek after the 3rd Ode) [these Kathismata, however, belong to the First Stasis of the Matins of March 9, according to the Menaion]; "Glory... Both now and ever...": **"The great commander"** (*Ὁ μέγας στρατηγός*); at the 2nd Stichologia: of the Saints: **"Enlisted under Christ"** (*Τῷ Χριστῷ στρατευθέντες*); "Glory... Both now and ever...": **"I reflect upon the judgment"** (*Ἐνθυμοῦμαι τὴν κρίσιν*) [these Kathismata of the Second Stasis follow the 3rd Ode]; and immediately Psalm 50 [LXX] read plainly. Canons: that of the Theotokos: **"I shall open my mouth"** (*Ἀνοίξω τὸ στόμα μου*), and that of the Saints; after the 3rd Ode, the Kathisma: **"The great commander"** (*Ὁ μέγας στρατηγός*) once; after the 6th Ode, the Kontakion: **"To thee, the Champion Leader"** (*Τῇ ὑπερμάχῳ*), and the Ikos: **"An archangel was sent"** (*Ἄγγελος πρωτοστάτης*), the Menologion of the Martyrs, and the Synaxarion of the Triodion; the Katavasiai: **"I shall open my mouth"**; and we chant "More honorable than the Cherubim". Exapostilaria: of the Saints, and that of the Triodion: **"Today the mystery that is from all eternity"** (*Τὸ ἀπ᾿ αἰῶνος σήμερον*). At the Praises: 3 Prosomia of the Theotokos: **"A hidden mystery"** (*Κεκρυμμένον μυστήριον*), and 3 of the Saints: **"Come, O brethren, let us praise in song the band of martyrs"** (*Δεῦτε μαρτυρικὴν ἀδελφοί*); "Glory...": **"O prize-bearing martyrs of Christ"** (*Ἀθλοφόροι Χριστοῦ*); "Both now and ever...": **"A tongue which she knew not"** (*Γλῶσσαν ἣν οὐκ ἔγνω*); Great Doxology, and the Dismissal Troparion: **"By reason of the sufferings which the Saints endured for Thy sake, O Lord"** (*Τὰς ἀλγηδόνας τῶν Ἁγίων*).[^283]

=== LEAF p449 ===

# Month of March: The Holy Forty Martyrs (Situation XII Concl. § 21); The Annunciation (Situation I § 1)

## Τῇ Θ΄: Τῶν Ἁγίων Μ΄ Μαρτύρων (Περίπτωσις ΙΒ΄ Τέλος § 21) [Violakis, p. 434]

21.    Τροπάρια ἀνὰ δ΄ ἐκ τῆς γ΄ Ὠδῆς τοῦ Κανόνος τῆς Θεοτόκου, καὶ ἐκ τῆς ς΄ τῶν Ἁγίων. Εἰς τὴν Εἴσοδον, Δεῦτε προσκυνήσωμεν... ὁ ἐν Ἁγίοις θαυμαστός, Τὸ προσταχθὲν μυστικῶς, τὸ τῶν Ἁγίων, τὸ τοῦ Ἁγίου τοῦ Ναοῦ, καὶ Κοντάκιον Τῇ ὑπερμάχῳ. Ἀπόστολος τῶν Ἁγίων καὶ Εὐαγγέλιον Ἀναστᾶσα Μαριάμ. Εἰς τὸ Ἐξαιρέτως Ἅπας γηγενής· Κοινωνικὸν Ποτήριον σωτηρίου, Εἴδομεν τὸ φῶς, καὶ Ἀπόλυσις.
    Σημειωτέον ὅτι ἡ μνήμη τῶν Μ΄ Μαρτύρων δύναται νὰ συμπέσῃ ἐν τῷ Τριῳδίῳ ἀπὸ τῆς Τετάρτης τῆς Α΄ ἑβδομάδος τῶν Νηστειῶν, μέχρι τῆς Δευτέρας τῶν Βαΐων (Ὅρα τὸν τοῦ Ἑορτοδρομίου Πίνακα).

# The 25th Day of March: The Annunciation of Our Most Holy Lady, the Theotokos and Ever-Virgin Mary

## Τῇ ΚΕ΄: Ὁ Εὐαγγελισμὸς τῆς Θεοτόκου (Σημείωσις Παραμονῆς, Περίπτωσις Α΄ § 1) [Violakis, p. 434]

### ΠΕΡΙΠΤΩΣΕΙΣ

#### Α΄.

Σημείωσις.    Ἐὰν ἡ παραμονὴ τῆς ἑορτῆς τοῦ Εὐαγγελισμοῦ τύχῃ ἐν ἡμέρᾳ Τετάρτῃ ἢ Παρασκευῇ, ἐν αἷς, ὡς ἔθος, τελεῖται Προηγιασμένη Λειτουργία, ἐν μὲν ταῖς Ἱεραῖς Ἐκκλησίαις τῶν πόλεων οὐ τελεῖται Προηγιασμένη διὰ τὸ μηδὲ ἀγρυπνίαν τελεῖσθαι ἐν ταύταις ἐξαιρουμένης τῆς Μεγάλης Τρίτης καὶ Μ. Τετάρτης, ἐν αἷς τελεῖται Προηγιασμένη μετὰ μικροῦ Ἑσπερινοῦ. Ἐν ταῖς Ἱεραῖς ὅμως Μοναῖς διὰ τὴν διαφορὰν τοῦ μοναχικοῦ βίου καὶ διὰ τὸ τελεῖσθαι πάντοτε ἐν ταύταις ἀγρυπνίαν, τελεῖται τῇ παραμονῇ Προηγιασμένη μετὰ μικροῦ Ἑσπερινοῦ, τῶν ἀρχαίων κτητορικῶν Τυπικῶν ἀμετακινήτων διαμενόντων.
1.    Εἰ τύχοι ὁ Εὐαγγελισμὸς τῇ Παρασκευῇ τῆς Γ΄ ἑβδομάδος τῶν Νηστειῶν, τῇ Τετάρτῃ πρωῒ ἐν τῷ Ἑσπερινῷ τῆς Προηγιασμένης Λειτουργίας, μετὰ τὸν Προοιμιακὸν καὶ τὰ Πρὸς Κύριον, εἰς τὸ Κύριε ἐκέκραξα ψάλλεται (ἐκ τοῦ Τριῳδίου) τὸ Ἰδιόμελον τῆς ἡμέρας δὶς καὶ τὸ Μαρτυρικὸν ἅπαξ· τὰ γ΄ τοῦ Τριῳδίου τῆς σειρᾶς Προσόμοια καὶ δ΄ Προεόρτια Κεκρυμμένον Μυστήριον· Δόξα, Καὶ νῦν, Εὐαγγελίζεται ὁ Γαβριὴλ Εἴσοδος Φῶς ἱλαρόν, καὶ τὰ Ἀναγνώσματα τῆς ἡμέρας, τὸ Κατευθυνθήτω, καὶ καθεξῆς ἡ

=== LEAF p450 ===

# Month of March: The Holy Forty Martyrs (Situation XII Concl. § 21); The Annunciation (Situation I § 1)

## March 9: The Holy Forty Martyrs [in the Lake of Sebastea] (Situation XII Concl. § 21) [Violakis, p. 435]

21.    At the Divine Liturgy, the Typika and the Beatitudes: 4 troparia from the 3rd Ode of the Canon of the Theotokos, and 4 from the 6th Ode of that of the Saints. At the Entrance: **"O come, let us worship and bow down before Christ; save us, O Son of God, wondrous art Thou in the Saints, who sing to Thee: Alleluia"** (*Δεῦτε προσκυνήσωμεν... ὁ ἐν Ἁγίοις θαυμαστός*), **"Taking knowledge of the secret command"** (*Τὸ προσταχθὲν μυστικῶς*), that of the Saints, that of the Patron Saint of the Church, and the Kontakion: **"To thee, the Champion Leader"** (*Τῇ ὑπερμάχῳ*). Epistle of the Saints and Gospel: **"Mary arose"** (*Ἀναστᾶσα Μαριάμ*, Luke 1:39–49, 56). At "Especially": **"Let all earth-born mortals rejoice in spirit"** (*Ἅπας γηγενής*); Communion Verse: **"I will take the cup of salvation, and I will call upon the name of the Lord"** (*Ποτήριον σωτηρίου*, Ps. 115:4 LXX); **"We have seen the true light"** (*Εἴδομεν τὸ φῶς τὸ ἀληθινόν*), and Dismissal.
    Note that the commemoration of the Holy Forty Martyrs may concur within the Triodion period from Wednesday of the First Week of the Great Fast until Great and Holy Monday of Passion Week (See the Festal Paschalion Chart).

# The 25th Day of March: The Annunciation of Our Most Holy Lady, the Theotokos and Ever-Virgin Mary

## March 25: The Annunciation of Our Most Holy Lady, the Theotokos and Ever-Virgin Mary (Situation I § 1) [Violakis, p. 435]

### SITUATIONS

#### SITUATION ONE

Note: If the Paramony [Eve] of the Feast of the Annunciation falls on a Wednesday or Friday, on which days, according to custom, the Liturgy of the Presanctified Gifts is celebrated: in the holy parish churches of the cities the Presanctified Liturgy is not celebrated, because an all-night vigil is not kept in them (except on Great and Holy Tuesday and Great and Holy Wednesday, on which the Presanctified Liturgy is celebrated following Small Vespers). In the holy monasteries, however, owing to the distinction of the monastic way of life and because all-night vigils are always celebrated therein, the Presanctified Liturgy is celebrated on the Paramony following Small Vespers, the ancient monastic typika remaining immovable.
1.    If the Feast of the Annunciation falls on Friday of the 3rd Week of the Great Fast: on Wednesday morning at the Vespers of the Presanctified Liturgy, after the Introductory Psalm [Ps. 103 LXX] and "Unto the Lord" [Kathisma 18, Pss. 119–133 LXX], at "Lord, I have cried", we sing [from the Triodion] the Idiomelon of the day twice, and the Martyrikon once; then the 3 Prosomia of the sequence of the Triodion, and 4 Forefeast Prosomia: **"A hidden mystery"** (*Κεκρυμμένον μυστήριον*); "Glory... Both now and ever...": **"Gabriel announces"** (*Εὐαγγελίζεται ὁ Γαβριὴλ*); Little Entrance, "O Gladsome Light", and the Readings of the day; then **"Let my prayer arise"** [Ps. 140:2 LXX], and the Liturgy of the Presanctified Gifts follows in due order. Then in the evening, the Great[^284]
"""

FOOTNOTES_TEXT = """[^280]: March 9: Commemoration of the Holy Forty Martyrs of Sebastea — Situation VI Conclusion, Situation VII (§ 12), and Situation VIII Opening (§ 13): Concurrence on Monday of Weeks 2–6, Wednesday of the 4th Week (Mid-Lent), and Saturdays of Weeks 2–4 of Great Lent. Detailed epigraphic synthesis of physical leaf p441 (printed page 426) and facing English leaf p442 (printed page 427). The conclusion of Situation VI directs that when the feast falls on Monday morning, the Service of Matins, the Hours, and the Liturgy of the Presanctified Gifts follow Situation I, Paragraphs 2 and 3; if on Tuesday of Weeks 2, 3, 4, or 5, Vespers of the Presanctified appoints the Idiomelon of the Aposticha twice, the Martyrikon once, 3 Prosomia of the sequence, and 4 of the Saints; Doxastikon of the Saints, Stavrotheotokion, as in Situation I, Paragraphs 2 and 3. Paragraph 12 establishes Situation VII: when the feast falls on Mid-Lent Wednesday (Wednesday of the 4th Week), Matins follows Situation I, Paragraphs 2 and 3; the Hours are read plainly, replacing the standard Lenten Troparia with the veneration of the Precious Cross: "Thy Cross do we adore, O Master" (*Τὸν Σταυρόν σου Προσκυνοῦμεν Δέσποτα*), Dismissal Troparion *Τὰς ἀλγηδόνας τῶν Ἁγίων*, and Kontakion *Οὐκέτι φλογίνη ῥομφαία*; at Vespers, after Kathisma 18 of the Psalter, at "Lord, I have cried", 10 Stichira combine the 2 Idiomela and the Martyrikon, 3 Prosomia of the Triodion, and 4 of the Saints; Doxastikon *Τὴν λίμνην ὡς παράδεισον*, Theotokion *Σήμερον ὁ ἀπρόσιτος τῇ οὐσίᾳ*, Little Entrance with the Holy Gospel Book, "O Gladsome Light", Readings of the day, *Κατευθυνθήτω*, Epistle and Gospel of the Martyrs, Presanctified Liturgy with Communion Verse Psalm 111:6 LXX (*Εἰς μνημόσυνον*), and Dismissal. Paragraph 13 establishes Situation VIII: when the feast falls on Saturday of Weeks 2, 3, or 4 of Great Lent, on Friday morning at Vespers, 10 Stichira at "Lord, I have cried" combine the day's Idiomelon twice, 4 Martyrika in the Tone occurring, and 4 of the Saints; Doxastikon *Ἐν ᾠδαῖς ᾀσμάτων*, first Theotokion of the Tone, Little Entrance with the censer, "O Gladsome Light", Readings, *Κατευθυνθήτω*, Presanctified Liturgy with Communion Verse Psalm 33:9 LXX (*Γεύσασθε καὶ ἴδετε*), and Dismissal; on Friday evening, the Oikoi of the Theotokos (Akathist Stasis) are read as customary, with Kontakion *Πᾶσαν στρατιάν*.

[^281]: March 9: Commemoration of the Holy Forty Martyrs of Sebastea — Situation VIII Conclusion (§ 13 concl.), Situation IX (§ 14), and Situation X Opening (§ 15): Concurrence on Saturdays of Weeks 2–4, Wednesday of the 5th Week, and Thursday of the Great Canon. Detailed epigraphic synthesis of physical leaf p443 (printed page 428) and facing English leaf p444 (printed page 429). The conclusion of Paragraph 13 establishes that on Saturday morning, Matins with the Divine Liturgy of St. John Chrysostom is celebrated according to the known order, with the Epistle and Gospel of the Saints and Communion Verse Psalm 111:6 LXX (*Εἰς μνημόσυνον*). Paragraph 14 establishes Situation IX: when the feast falls on Wednesday of the 5th Week of Great Lent, Matins and the Hours follow Situation I, Paragraph 2; at Vespers, after Kathisma 18, at "Lord, I have cried", beginning from the verse "The sinners shall fall into their net" (Psalm 140:10 LXX), the day's Idiomelon is chanted twice, then the Martyrikon, 3 Prosomia of the Triodion, 4 of the Saints (*Φέροντες τὰ παρόντα γενναίως*), followed by the 24 alphabetical Stichira of the Triodion (*Ἅπας ὁ βίος μου* through *Ὢ τῆς ἀφάτου σου εὐσπλαγχνίας*); Doxastikon *Τὴν λίμνην ὡς παράδεισον*, Theotokion *Ἔργοις σκοτεινοῖς συναπαχθείς*, Little Entrance with the Holy Gospel Book, "O Gladsome Light", Readings of the day, *Κατευθυνθήτω*, Epistle and Gospel of the Saints, Presanctified Liturgy with Communion Verse Psalm 111:6 LXX, and Dismissal; on Wednesday evening, the Great Canon of St. Andrew of Crete is chanted with Small Compline. Paragraph 15 establishes Situation X: when the feast falls on Thursday of the Great Canon, on Wednesday morning Vespers and the Presanctified Liturgy follow Paragraph 14 without the Epistle, Gospel, or Doxastikon, appointing Communion Verse Psalm 33:9 LXX (*Γεύσασθε καὶ ἴδετε*); on Thursday morning, after Psalm 50 LXX, the Trisagion Prayers, Dismissal Troparion of the Saints, Hexapsalmos, and "God is the Lord"; Psalter, Kathismata of the Saints with their Theotokia, Psalm 50 read plainly, Odes 1 and 3 of the Saints' Canon, Kathisma of the Saints, Ode 4 of the Triodion and Saints, Odes 5 and 6 of the Saints, Little Litany, Kontakion of the Great Canon (*Ψυχή μου ψυχή μου*), and Menologion of the Martyrs; then Ode 7, which was inadvertently omitted in the printed Greek text due to typographical haplography, is supplied in the liturgical order.

[^282]: March 9: Commemoration of the Holy Forty Martyrs of Sebastea — Situation X Conclusion (§§ 15–16) and Situation XI (§§ 17–18): Concurrence on Thursday of the Great Canon and Friday of the 5th Week of Great Lent. Detailed epigraphic synthesis of physical leaf p445 (printed page 430) and facing English leaf p446 (printed page 431). The conclusion of Paragraph 15 details Matins of Thursday of the Great Canon: following the supplied 7th Ode, Odes 8 and 9 of the Triodion and the Saints are chanted; Katavasiai *Ἀνοίξω τὸ στόμα μου*; "More honorable than the Cherubim"; Exapostilaria of the Saints and Theotokion; at the Praises, Prosomia *Δεῦτε μαρτυρικὴν ἀδελφοί*, Doxastikon *Ἀθλοφόροι Χριστοῦ*, Theotokion *Μακαρίζομέν σε*, Great Doxology, Dismissal Troparion of the Martyrs; the Hours are read plainly with Dismissal Troparion *Τὰς ἀλγηδόνας τῶν Ἁγίων* and Kontakion *Ψυχή μου ψυχή μου*; at the 9th Hour, the Beatitudes and remainder follow St. Charalampos Situation VIII, Paragraph 14. Paragraph 16 governs Thursday Vespers: after Kathisma 18, at "Lord, I have cried", 10 Stichira combine the Idiomelon *Αὐτεξουσίως ἐξεδόθην* twice, Martyrikon, 3 Prosomia of the Triodion, and 4 of the Saints; Doxastikon *Ἐν ᾠδαῖς ᾀσμάτων*, Prosomion Stavrotheotokion, Little Entrance with the Holy Gospel Book, "O Gladsome Light", Readings of the day, *Κατευθυνθήτω*, Epistle and Gospel of the Saints, Presanctified Liturgy with Communion Verse Psalm 111:6 LXX, and Dismissal. Paragraph 17 establishes Situation XI: when the feast falls on Friday of the 5th Week, on Thursday morning at Vespers, the Idiomelon, Martyrikon, 3 Prosomia of the sequence, and 4 of the Martyrs are chanted; on Friday morning, Matins and the Hours follow Situation I, Paragraph 2. Paragraph 18 governs Friday Vespers: after Kathisma 18, at "Lord, I have cried", 10 Stichira combine the Idiomelon *Ὡς ἐξ Ἱερουσαλὴμ* twice, 4 Prosomia of the Theotokos *Βουλὴν προαιώνιον*, and 4 of the Saints; Doxastikon *Τὴν λίμνην ὡς παράδεισον*, Theotokion *Τὸ ἀπ᾿ αἰῶνος μυστήριον*, Little Entrance with the Holy Gospel Book, "O Gladsome Light", Readings of the day, *Κατευθυνθήτω*, Epistle and Gospel of the Saints, Presanctified Liturgy with Communion Verse Psalm 111:6 LXX, and Dismissal.

[^283]: March 9: Commemoration of the Holy Forty Martyrs of Sebastea — Situation XI Conclusion and Situation XII Opening (§§ 19–20): Concurrence on Friday of the 5th Week and Saturday of the Akathist (5th Saturday of Great Lent). Detailed epigraphic synthesis of physical leaf p447 (printed page 432) and facing English leaf p448 (printed page 433). The conclusion of Situation XI notes that on Friday evening the Akathist Hymn (complete stases) is chanted with Small Compline and Kontakion *Τῇ ὑπερμάχῳ*. Paragraph 19 establishes Situation XII: when the feast falls on the Saturday of the Akathist Hymn: on Friday morning at Vespers, after Kathisma 18, at "Lord, I have cried", 10 Stichira combine the Idiomelon *Ὡς ἐξ Ἱερουσαλὴμ* twice, 4 Prosomia of the Theotokos *Βουλὴν προαιώνιον*, and 4 of the Martyrs; Doxastikon *Προφητικῶς ἀνεβόα*, Theotokion *Τὸ ἀπ᾿ αἰῶνος μυστήριον*, Little Entrance with the censer, "O Gladsome Light", Readings of the day, *Κατευθυνθήτω*, Presanctified Liturgy with Communion Verse Psalm 33:9 LXX (*Γεύσασθε καὶ ἴδετε*), and Dismissal; on Friday evening, the Akathist Hymn is sung with Small Compline and Kontakion *Τῇ ὑπερμάχῳ*. Paragraph 20 details Saturday Matins: Midnight Service, Trisagion Prayers, Troparion *Τὸ προσταχθὲν μυστικῶς*, and Hexapsalmos; at "God is the Lord", *Τὸ προσταχθὲν μυστικῶς*, Dismissal Troparion of the Martyrs *Τὰς ἀλγηδόνας τῶν Ἁγίων*, and again *Τὸ προσταχθὲν μυστικῶς*; Psalter; Kathismata of the Saints *Τὸ σεπτὸν στερέωμα* (noting that the Greek text cross-references this after Ode 3, whereas in the Menaion it belongs to the First Stasis of Matins for March 9); Doxastikon *Ὁ μέγας στρατηγός*; at the 2nd Stichologia, Kathisma *Τῷ Χριστῷ στρατευθέντες*, Doxastikon *Ἐνθυμοῦμαι τὴν κρίσιν* (which follow Ode 3 in the Menaion); Psalm 50 LXX read plainly; Canons of the Theotokos *Ἀνοίξω τὸ στόμα μου* and the Saints; after Ode 3, Kathisma *Ὁ μέγας στρατηγός* once; after Ode 6, Kontakion *Τῇ ὑπερμάχῳ*, Ikos *Ἄγγελος πρωτοστάτης*, Menologion of the Martyrs, and Synaxarion of the Triodion; Katavasiai *Ἀνοίξω τὸ στόμα μου*; "More honorable than the Cherubim"; Exapostilaria of the Saints and Triodion *Τὸ ἀπ᾿ αἰῶνος σήμερον*; at the Praises, 3 Prosomia of the Theotokos *Κεκρυμμένον μυστήριον* and 3 of the Saints *Δεῦτε μαρτυρικὴν ἀδελφοί*; Doxastikon *Ἀθλοφόροι Χριστοῦ*, Theotokion *Γλῶσσαν ἣν οὐκ ἔγνω*, Great Doxology, and Dismissal Troparion *Τὰς ἀλγηδόνας τῶν Ἁγίων*. Paragraph 21 commences at the foot of leaf p447.

[^284]: March 9: Commemoration of the Holy Forty Martyrs of Sebastea — Situation XII Conclusion (§ 21, Festal Range Note); March 25: The Annunciation of the Most Holy Theotokos — Paramony Rubric and Situation I Opening (§ 1). Detailed epigraphic synthesis of physical leaf p449 (printed page 434) and facing English leaf p450 (printed page 435). Paragraph 21 concludes Situation XII: at the Divine Liturgy of St. John Chrysostom, Typika and Beatitudes appoint 4 troparia from Ode 3 of the Theotokos and 4 from Ode 6 of the Saints; at the Little Entrance, the Third Antiphon refrain is chanted: "O come, let us worship and bow down before Christ; save us, O Son of God, wondrous art Thou in the Saints, who sing to Thee: Alleluia", followed by Troparion *Τὸ προσταχθὲν μυστικῶς*, that of the Saints, the Temple Patron, and Kontakion *Τῇ ὑπερμάχῳ*; Epistle of the Saints and Gospel *Ἀναστᾶσα Μαριάμ* (Luke 1:39–49, 56); Megalynarion at "Especially": *Ἅπας γηγενής*; Communion Verse: Psalm 115:4 LXX (*Ποτήριον σωτηρίου*); *Εἴδομεν τὸ φῶς*, and Dismissal. The general rubric notes that the Feast of the Forty Martyrs can fall within the Triodion cycle between Wednesday of the First Week of Great Lent and Great and Holy Monday of Passion Week. For March 25 (The Annunciation of the Most Holy Theotokos), the Paramony Rubric distinguishes cathedral/parish usage from monastic typika: when the Eve falls on Wednesday or Friday, parish churches do not celebrate the Presanctified Liturgy because they do not hold an all-night vigil (except on Great and Holy Tuesday and Wednesday), whereas monasteries celebrate the Presanctified Liturgy combined with Small Vespers according to ancient founder typika. Paragraph 1 establishes Situation I: when the Annunciation falls on Friday of the 3rd Week of Great Lent, on Wednesday morning at Vespers of the Presanctified, after Kathisma 18, at "Lord, I have cried", 10 Stichira combine the day's Idiomelon twice, Martyrikon once, 3 Prosomia of the sequence of the Triodion, and 4 Forefeast Prosomia *Κεκρυμμένον μυστήριον*; Doxastikon *Εὐαγγελίζεται ὁ Γαβριὴλ*, Little Entrance with "O Gladsome Light", Readings of the day, *Κατευθυνθήτω*, and the Liturgy of the Presanctified Gifts follows in due order.
"""

draft_path = Path("Liturgical Monuments/Monument 5 - 1888 Violakis Typikon/Draft/1888_violakis_typikon_cohort45_raw_draft.md")
draft_path.write_text(DRAFT_TEXT.strip() + "\n", encoding='utf-8')
print(f"Wrote draft: {draft_path} ({len(DRAFT_TEXT)} chars)")

fn_path = Path("Liturgical Monuments/Monument 5 - 1888 Violakis Typikon/Draft/1888_violakis_typikon_cohort45_footnotes.txt")
fn_path.write_text(FOOTNOTES_TEXT.strip() + "\n", encoding='utf-8')
print(f"Wrote footnotes: {fn_path} ({len(FOOTNOTES_TEXT)} chars)")
