import sys
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')

footnotes = {
    1183: "See above, p. 200.",
    1184: "The monasteries in the environs of Antioch are described by St. John Chrysostom, *In Matthaeum hom.* 68, 70 (Migne, *PG*, t. 58, cols. 644–646, 659–662).",
    1185: "Bollandists, *Acta Sanctorum*, Jan. I, p. 118; *Menologion* of St. Demetrius of Rostov (*Chet'i Minei*), July 3.",
    1186: "*Menologion* of St. Demetrius of Rostov (*Chet'i Minei*), Dec. 29.",
    1187: "Du Cange, *Constantinopolis Christiana*, Venice 1729, lib. IV, cap. 10, p. 105.",
    1188: "Archbishop Sergius (Spassky), *Complete Menologion of the East* (*Polny mesiatseslov Vostoka*), Vladimir 1901, vol. II, p. 465.",
    1189: "Michael Glykas (XIII c.), *Annales*, cited in Du Cange, *Constantinopolis Christiana*, lib. IV, cap. 8, p. 70. A Stoudios is likewise mentioned in the *Codex Theodosianus* under Emperor Arcadius (in 401 and 404), as *Comes rerum privatarum*, and in Justinian's *Novella 59*. Unto Stoudios there exists an epistle of St. John Chrysostom wherein the holy father consoles him upon the death of his brother; Palladius in the *Life of Chrysostom* called this Stoudios prefect of the city (Du Cange, *ibid.*).",
    1190: "Du Cange, *Constantinopolis Christiana*, lib. IV, cap. 8, p. 70.",
    1191: "Du Cange, *ibid.*",
    1192: "The Stoudios Monastery was situated outside the city, near the Golden Gate and the sea, where today stands the İmrahor Mosque (*İmrahor Camii*). E. Marin, *De Studio coenobio Constantinopolitano*, Paris 1897, p. 3; Priest N. Grossu, *St. Theodore the Studite* (*Prepodobny Feodor Studit*), Kyiv 1907, p. 88.",
    1193: "Bollandists, *Acta Sanctorum*, Jun. II, p. 25; Archbishop Sergius, *Complete Menologion of the East*, June 7.",
    1194: "Pseudo-Codinus, *De aedificiis Constantinopolitanis*; Migne, *PG*, t. 157, col. 585.",
    1195: "*Vita S. Auxentii*; Migne, *PG*, t. 114, col. 1380.",
    1196: "S. Pétridès, \"Le monastère des Spoudaei à Jérusalem et les Spoudaei de Constantinople,\" *Échos d'Orient*, t. 4 (1901), pp. 225–231.",
    1197: "According unto Kodinos, Anna, the consort of Emperor Leo, upon returning home from Blachernae during her pregnancy was overtaken by labor, entered the house of a certain protospatharios, and gave birth there; this house was converted into a monastery, named on this occasion the monastery of \"urgency\" or \"haste\" (*σπουδῆς*) (Du Cange, *op. cit.*, lib. IV, cap. 11, p. 112).",
    1198: "Compare above, pp. 112 and 118, the juxtaposition in Origen of Friday and Sunday.",
    1199: "Eusebius, *Vita Constantini*, lib. IV, cap. 17–20; Migne, *PG*, t. 20, cols. 1164–1168.",
    1200: "*Codex Justiniani*, lib. III, tit. 12, lex 2 (al. 3).",
    1201: "*Codex Theodosianus*, lib. VIII, tit. 8, lex 1.",
    1202: "An edict concerning this, not preserved unto us, was reaffirmed by an edict of 386 AD and by Theodosius the Younger in 425 AD, with the extension of this prohibition unto imperial days occurring on Sunday (*Cod. Theod.*, lib. XV, tit. 5, lex 2; lib. XVI, tit. 11, lex 1).",
    1203: "*Ibid.*, lib. VIII, tit. 8, lex 3.",
    1204: "*Ibid.*, lib. II, tit. 8, lex 2. These laws were incorporated into the *Codex Justiniani* as well. Emperor Leo VI the Wise (886–911) prohibited agricultural labor on Sunday as well (*Novella 65*). D. Smirnov, *The Celebration of the Sunday Day* (*Prazdnovanie voskresnogo dnya*), p. 178.",
    1205: "*Apostolic Constitutions*, II, 60; Caesarius of Arles, *Sermo 12* (al. 280).",
    1206: "St. John Chrysostom, *De sancta Pentecoste hom.* 1, § 1; Migne, *PG*, t. 50, col. 454.",
    1207: "St. John Chrysostom, *Homilia in sanctum Baptisma*; Migne, *PG*, t. 49, col. 364.",
    1208: "St. John Chrysostom, *In Matthaeum hom.* 5, § 1; Migne, *PG*, t. 57, col. 55.",
    1209: "St. Augustine, *Enarratio in Psalmum 91*, § 2; Migne, *PL*, t. 37, col. 1172: \"melius enim faceret in agro suo aliquid utile, quam in theatro seditiosus exsisteret... melius tota die foderent, quam tota die saltarent.\"",
    1210: "Council of Sardica, Canon 11. A canon confirmed by Canon 80 of the Trullan Council (Council in Trullo), with the admission of an exception for severe necessity or insurmountable hindrances.",
    1211: "See above, p. 148.",
    1212: "See above, pp. 207, 216.",
    1213: "Compare above, p. 149.",
    1214: "Sozomen, *Historia Ecclesiastica*, lib. VIII, cap. 8; Socrates, *Historia Ecclesiastica*, lib. VI, cap. 8.",
    1215: "Pseudo-Athanasius, *Quaestiones ad Antiochum ducem*, Quaest. 55; Migne, *PG*, t. 28, col. 632; compare above, pp. 191, 230: Sunday vigils of SS. Arsenius and Simeon Stylites.",
    1216: "St. John Chrysostom, *De incomprehensibili Dei natura homiliae*. In agreement with this, Canon 90 of the Trullan Council (Council in Trullo) commandeth to begin the celebration of the Sunday day from Saturday evening and to conclude it at the onset of Sunday evening.",
    1217: "See above, pp. 112–113.",
    1218: "*Apostolic Constitutions*, II, 59; see above, p. 113.",
    1219: "*Apostolic Constitutions*, V, 20.",
    1220: "*Apostolic Constitutions*, VII, 23.",
    1221: "*Apostolic Constitutions*, VIII, 33.",
    1222: "Socrates, *Historia Ecclesiastica*, lib. VI, cap. 8; see above, p. 263.",
    1223: "St. Basil the Great, *Epistle 93* [al. 89]; St. John Chrysostom, *In 1 Tim. hom.* 5, § 3; Timothy of Alexandria, *Canon 13*.",
    1224: "Socrates, *Historia Ecclesiastica*, lib. V, cap. 22; compare above, pp. 191, 195, 196, 201: Saturday among the anchorites and in monasteries.",
    1225: "St. John Cassian, *De institutis coenobiorum*, lib. III, cap. 8–9; see above, p. 148.",
    1226: "Th. Zahn, *Geschichte des Sonntags*, Hannover 1878, p. 75; V. Rybinsky, *The Ancient Hebrew Sabbath* (*Drevne-evreyskaya subbota*), Kyiv 1892, p. 253.",
    1227: "Preserved unto this day in the Abyssinian Church, wherein Saturday is celebrated on an equality with Sunday (*ibid.*).",
    1228: "Council of Laodicea, Canon 29.",
    1229: "St. John Cassian, *De institutis coenobiorum*, lib. III, cap. 10.",
    1230: "*Apostolic Constitutions*, VII, 23 (al. 24).",
    1231: "*Apostolic Canons*, Canon 69.",
    1232: "St. Epiphanius of Cyprus, *Expositio fidei*, § 22; Migne, *PG*, t. 42, cols. 825–828.",
    1233: "See above, p. 119.",
    1234: "Eusebius, *Vita Constantini*, lib. IV, cap. 18; Sozomen, *Historia Ecclesiastica*, lib. I, cap. 8.",
    1235: "St. Basil the Great, *Epistle 93* [al. 89], see above, p. 164; St. Ambrose, *Enarratio in Psalmum 118*, sermo 8, § 48.",
    1236: "Socrates, *Historia Ecclesiastica*, lib. V, cap. 22.",
    1237: "A. Mai, *Spicilegium Romanum*, t. IV, p. 32; E. Renaudot, *Liturgiarum orientalium collectio*, Paris 1716, t. I, p. 79.",
    1238: "First Ecumenical Council of Nicaea, Canon 5.",
    1239: "Eusebius of Caesarea, *De solemnitate paschali*, cap. 4–5; Migne, *PG*, t. 24, cols. 697–701.",
    1240: "St. Athanasius the Great, *Epistola heortastica 2* (a. 330), § 7; *Epistola encyclica ad episcopos*, § 4; *Apologia ad Constantium*, § 15.",
    1241: "St. Cyril of Jerusalem, *Catechesis* 4; *Mystagogica* 4.",
    1242: "Council of Laodicea, Canons 49, 51.",
    1243: "St. Epiphanius of Cyprus, *Expositio fidei*, § 21; Migne, *PG*, t. 42, col. 825.",
    1244: "St. Ambrose of Milan, *De Noe et arca*, cap. 4; *De Helia et ieiunio*, cap. 10.",
    1245: "Socrates, *Historia Ecclesiastica*, lib. V, cap. 22.",
    1246: "Sozomen, *Historia Ecclesiastica*, lib. VII, cap. 19.",
    1247: "The author of the *Historical Discourse on the Fasts of the Orthodox Eastern Catholic Church* (Moscow 1837) (Hieromonk Alexis Soloviev) suspecteth the testimonies of Socrates and Sozomen concerning the diverse duration and time of the pre-Paschal fast of inaccuracy and even of deliberate distortion of the truth, explaining the latter by their inclination toward Novatianism: \"The positive ordinances of the Church could not please them; thence it certainly arose that it was deemed necessary intentionally and with effort to seek out differences in the rites of the Church, and in doing so to mingle half-truth with truth or with falsehood\" (p. 17). Yet of the ordinances of the Church, the forty-day fast was the least likely to displease the Novatians, the Christian rigorists of that day.",
    1248: "F. X. Funk, *Kirchengeschichtliche Abhandlungen und Untersuchungen*, Bd. I, Paderborn 1897, S. 264.",
    1249: "Funk, *ibid.*",
    1250: "*Apostolic Canons*, Canon 66.",
    1251: "St. Cyril of Jerusalem, *Catechesis* 18, although the word \"Forty-Day Fast\" (*Tessarakoste*) might already have been for him a *terminus technicus*.",
    1252: "*Peregrinatio ad loca sancta* (*Pilgrimage of Egeria*), § 27.",
    1253: "In the epistle of St. John Damascene on fasting there is a reference unto this testimony: Migne, *PG*, t. 95, cols. 71–78.",
    1254: "Socrates, *Historia Ecclesiastica*, lib. V, cap. 22.",
    1255: "Such grounds are indicated by Durandus in his work *Rationale divinorum officiorum* (lib. VI, cap. 26), cited in H. Alt, *Das Kirchenjahr*, Berlin 1860, S. 20.",
    1256: "St. Ambrose, *Enarratio in Psalmum 118*, sermo 8, § 48; Migne, *PL*, t. 15, col. 1318.",
    1257: "St. Basil the Great, *Homilia 1 de ieiunio*, § 10; Migne, *PG*, t. 31, col. 181.",
    1258: "St. John Chrysostom, *Homiliae in Genesim*, hom. 4, § 2; hom. 6, § 1; Migne, *PG*, t. 53, cols. 42, 53.",
    1259: "St. Augustine, *Sermo 8* (*De ieiunio et eleemosyna*) [al. *Sermo 210*], § 10; Migne, *PL*, t. 38, col. 1052."
}

out_path = Path('Liturgical Monuments/Monument 6 - 1910 Skaballanovich Typikon/Draft/1910_skaballanovich_typikon_cohort23_footnotes.txt')

with open(out_path, 'w', encoding='utf-8') as f:
    for n in range(1183, 1260):
        f.write(f"[^{n}]: {footnotes[n]}\n")

print(f"Wrote {out_path}, total {len(footnotes)} footnotes (1183..1259).")
